// Code generated by MockGen. DO NOT EDIT.
// Source: actions.go
//
// Generated by this command:
//
//	mockgen -source=actions.go -destination=./actions/actions_mock.go -package=actions
//

// Package actions is a generated GoMock package.
package actions

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockActions is a mock of Actions interface.
type MockActions struct {
	ctrl     *gomock.Controller
	recorder *MockActionsMockRecorder
	isgomock struct{}
}

// MockActionsMockRecorder is the mock recorder for MockActions.
type MockActionsMockRecorder struct {
	mock *MockActions
}

// NewMockActions creates a new mock instance.
func NewMockActions(ctrl *gomock.Controller) *MockActions {
	mock := &MockActions{ctrl: ctrl}
	mock.recorder = &MockActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActions) EXPECT() *MockActionsMockRecorder {
	return m.recorder
}

// Redeem mocks base method.
func (m *MockActions) Redeem(ctx context.Context, rawToken, ip string) (entity.ActionOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeem", ctx, rawToken, ip)
	ret0, _ := ret[0].(entity.ActionOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redeem indicates an expected call of Redeem.
func (mr *MockActionsMockRecorder) Redeem(ctx, rawToken, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockActions)(nil).Redeem), ctx, rawToken, ip)
}
