// Code generated by MockGen. DO NOT EDIT.
// Source: user_identity.go
//
// Generated by this command:
//
//	mockgen -source=user_identity.go -destination=./user_identity/user_identity_mock.go -package=user_identity
//

// Package user_identity is a generated GoMock package.
package user_identity

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserIdentity is a mock of UserIdentity interface.
type MockUserIdentity struct {
	ctrl     *gomock.Controller
	recorder *MockUserIdentityMockRecorder
	isgomock struct{}
}

// MockUserIdentityMockRecorder is the mock recorder for MockUserIdentity.
type MockUserIdentityMockRecorder struct {
	mock *MockUserIdentity
}

// NewMockUserIdentity creates a new mock instance.
func NewMockUserIdentity(ctrl *gomock.Controller) *MockUserIdentity {
	mock := &MockUserIdentity{ctrl: ctrl}
	mock.recorder = &MockUserIdentityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIdentity) EXPECT() *MockUserIdentityMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserIdentity) Create(ctx context.Context, userID, connectionID, subject, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, connectionID, subject, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserIdentityMockRecorder) Create(ctx, userID, connectionID, subject, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserIdentity)(nil).Create), ctx, userID, connectionID, subject, email)
}

// GetBySubject mocks base method.
func (m *MockUserIdentity) GetBySubject(ctx context.Context, connectionID, subject string) (entity.UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubject", ctx, connectionID, subject)
	ret0, _ := ret[0].(entity.UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubject indicates an expected call of GetBySubject.
func (mr *MockUserIdentityMockRecorder) GetBySubject(ctx, connectionID, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubject", reflect.TypeOf((*MockUserIdentity)(nil).GetBySubject), ctx, connectionID, subject)
}
