// Code generated by MockGen. DO NOT EDIT.
// Source: policy.go
//
// Generated by this command:
//
//	mockgen -source=policy.go -destination=./policy/policy_mock.go -package=policy
//

// Package policy is a generated GoMock package.
package policy

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicy is a mock of Policy interface.
type MockPolicy struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyMockRecorder
	isgomock struct{}
}

// MockPolicyMockRecorder is the mock recorder for MockPolicy.
type MockPolicyMockRecorder struct {
	mock *MockPolicy
}

// NewMockPolicy creates a new mock instance.
func NewMockPolicy(ctrl *gomock.Controller) *MockPolicy {
	mock := &MockPolicy{ctrl: ctrl}
	mock.recorder = &MockPolicyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicy) EXPECT() *MockPolicyMockRecorder {
	return m.recorder
}

// Allowed mocks base method.
func (m *MockPolicy) Allowed(ctx context.Context, subject, workspaceID string, obj entity.PolicyObject, act entity.PolicyAction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allowed", ctx, subject, workspaceID, obj, act)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allowed indicates an expected call of Allowed.
func (mr *MockPolicyMockRecorder) Allowed(ctx, subject, workspaceID, obj, act any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allowed", reflect.TypeOf((*MockPolicy)(nil).Allowed), ctx, subject, workspaceID, obj, act)
}

// AssignAgentRole mocks base method.
func (m *MockPolicy) AssignAgentRole(ctx context.Context, workspaceID string, role entity.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignAgentRole", ctx, workspaceID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignAgentRole indicates an expected call of AssignAgentRole.
func (mr *MockPolicyMockRecorder) AssignAgentRole(ctx, workspaceID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignAgentRole", reflect.TypeOf((*MockPolicy)(nil).AssignAgentRole), ctx, workspaceID, role)
}

// AssignRole mocks base method.
func (m *MockPolicy) AssignRole(ctx context.Context, userID, workspaceID string, role entity.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, userID, workspaceID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockPolicyMockRecorder) AssignRole(ctx, userID, workspaceID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockPolicy)(nil).AssignRole), ctx, userID, workspaceID, role)
}

// CountActiveAdminsTx mocks base method.
func (m *MockPolicy) CountActiveAdminsTx(ctx context.Context, workspaceID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveAdminsTx", ctx, workspaceID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveAdminsTx indicates an expected call of CountActiveAdminsTx.
func (mr *MockPolicyMockRecorder) CountActiveAdminsTx(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveAdminsTx", reflect.TypeOf((*MockPolicy)(nil).CountActiveAdminsTx), ctx, workspaceID)
}

// RemoveRole mocks base method.
func (m *MockPolicy) RemoveRole(ctx context.Context, userID, workspaceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, userID, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockPolicyMockRecorder) RemoveRole(ctx, userID, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockPolicy)(nil).RemoveRole), ctx, userID, workspaceID)
}

// ReplaceRole mocks base method.
func (m *MockPolicy) ReplaceRole(ctx context.Context, userID, workspaceID string, from, to entity.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRole", ctx, userID, workspaceID, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceRole indicates an expected call of ReplaceRole.
func (mr *MockPolicyMockRecorder) ReplaceRole(ctx, userID, workspaceID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRole", reflect.TypeOf((*MockPolicy)(nil).ReplaceRole), ctx, userID, workspaceID, from, to)
}

// RoleOf mocks base method.
func (m *MockPolicy) RoleOf(ctx context.Context, userID, workspaceID string) (entity.Role, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleOf", ctx, userID, workspaceID)
	ret0, _ := ret[0].(entity.Role)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RoleOf indicates an expected call of RoleOf.
func (mr *MockPolicyMockRecorder) RoleOf(ctx, userID, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleOf", reflect.TypeOf((*MockPolicy)(nil).RoleOf), ctx, userID, workspaceID)
}

// RoleOfTx mocks base method.
func (m *MockPolicy) RoleOfTx(ctx context.Context, userID, workspaceID string) (entity.Role, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleOfTx", ctx, userID, workspaceID)
	ret0, _ := ret[0].(entity.Role)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RoleOfTx indicates an expected call of RoleOfTx.
func (mr *MockPolicyMockRecorder) RoleOfTx(ctx, userID, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleOfTx", reflect.TypeOf((*MockPolicy)(nil).RoleOfTx), ctx, userID, workspaceID)
}

// RolesByWorkspace mocks base method.
func (m *MockPolicy) RolesByWorkspace(ctx context.Context, workspaceID string) (map[string]entity.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RolesByWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].(map[string]entity.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RolesByWorkspace indicates an expected call of RolesByWorkspace.
func (mr *MockPolicyMockRecorder) RolesByWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RolesByWorkspace", reflect.TypeOf((*MockPolicy)(nil).RolesByWorkspace), ctx, workspaceID)
}

// SeedWorkspace mocks base method.
func (m *MockPolicy) SeedWorkspace(ctx context.Context, workspaceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SeedWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SeedWorkspace indicates an expected call of SeedWorkspace.
func (mr *MockPolicyMockRecorder) SeedWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SeedWorkspace", reflect.TypeOf((*MockPolicy)(nil).SeedWorkspace), ctx, workspaceID)
}
