// Code generated by MockGen. DO NOT EDIT.
// Source: api_key.go
//
// Generated by this command:
//
//	mockgen -source=api_key.go -destination=./api_key/api_key_mock.go -package=api_key
//

// Package api_key is a generated GoMock package.
package api_key

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIKey is a mock of APIKey interface.
type MockAPIKey struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyMockRecorder
	isgomock struct{}
}

// MockAPIKeyMockRecorder is the mock recorder for MockAPIKey.
type MockAPIKeyMockRecorder struct {
	mock *MockAPIKey
}

// NewMockAPIKey creates a new mock instance.
func NewMockAPIKey(ctrl *gomock.Controller) *MockAPIKey {
	mock := &MockAPIKey{ctrl: ctrl}
	mock.recorder = &MockAPIKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKey) EXPECT() *MockAPIKeyMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAPIKey) Create(ctx context.Context, rec entity.APIKeyRecord) (entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rec)
	ret0, _ := ret[0].(entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyMockRecorder) Create(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKey)(nil).Create), ctx, rec)
}

// GetByID mocks base method.
func (m *MockAPIKey) GetByID(ctx context.Context, workspaceID, id string) (entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, workspaceID, id)
	ret0, _ := ret[0].(entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAPIKeyMockRecorder) GetByID(ctx, workspaceID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAPIKey)(nil).GetByID), ctx, workspaceID, id)
}

// GetByTokenHash mocks base method.
func (m *MockAPIKey) GetByTokenHash(ctx context.Context, tokenHash string) (entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTokenHash indicates an expected call of GetByTokenHash.
func (mr *MockAPIKeyMockRecorder) GetByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTokenHash", reflect.TypeOf((*MockAPIKey)(nil).GetByTokenHash), ctx, tokenHash)
}

// ListByOwner mocks base method.
func (m *MockAPIKey) ListByOwner(ctx context.Context, workspaceID, ownerUserID string) ([]entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOwner", ctx, workspaceID, ownerUserID)
	ret0, _ := ret[0].([]entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOwner indicates an expected call of ListByOwner.
func (mr *MockAPIKeyMockRecorder) ListByOwner(ctx, workspaceID, ownerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOwner", reflect.TypeOf((*MockAPIKey)(nil).ListByOwner), ctx, workspaceID, ownerUserID)
}

// ListWorkspaceKeys mocks base method.
func (m *MockAPIKey) ListWorkspaceKeys(ctx context.Context, workspaceID string) ([]entity.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkspaceKeys", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkspaceKeys indicates an expected call of ListWorkspaceKeys.
func (mr *MockAPIKeyMockRecorder) ListWorkspaceKeys(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkspaceKeys", reflect.TypeOf((*MockAPIKey)(nil).ListWorkspaceKeys), ctx, workspaceID)
}

// Revoke mocks base method.
func (m *MockAPIKey) Revoke(ctx context.Context, workspaceID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, workspaceID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAPIKeyMockRecorder) Revoke(ctx, workspaceID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAPIKey)(nil).Revoke), ctx, workspaceID, id)
}

// TouchLastUsed mocks base method.
func (m *MockAPIKey) TouchLastUsed(ctx context.Context, id string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockAPIKeyMockRecorder) TouchLastUsed(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockAPIKey)(nil).TouchLastUsed), ctx, id, at)
}
