// Code generated by MockGen. DO NOT EDIT.
// Source: sso_connection.go
//
// Generated by this command:
//
//	mockgen -source=sso_connection.go -destination=./sso_connection/sso_connection_mock.go -package=sso_connection
//

// Package sso_connection is a generated GoMock package.
package sso_connection

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSSOConnection is a mock of SSOConnection interface.
type MockSSOConnection struct {
	ctrl     *gomock.Controller
	recorder *MockSSOConnectionMockRecorder
	isgomock struct{}
}

// MockSSOConnectionMockRecorder is the mock recorder for MockSSOConnection.
type MockSSOConnectionMockRecorder struct {
	mock *MockSSOConnection
}

// NewMockSSOConnection creates a new mock instance.
func NewMockSSOConnection(ctrl *gomock.Controller) *MockSSOConnection {
	mock := &MockSSOConnection{ctrl: ctrl}
	mock.recorder = &MockSSOConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSOConnection) EXPECT() *MockSSOConnectionMockRecorder {
	return m.recorder
}

// ClientSecret mocks base method.
func (m *MockSSOConnection) ClientSecret(ctx context.Context, workspaceID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientSecret", ctx, workspaceID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientSecret indicates an expected call of ClientSecret.
func (mr *MockSSOConnectionMockRecorder) ClientSecret(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientSecret", reflect.TypeOf((*MockSSOConnection)(nil).ClientSecret), ctx, workspaceID)
}

// Get mocks base method.
func (m *MockSSOConnection) Get(ctx context.Context, workspaceID string) (entity.SSOConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, workspaceID)
	ret0, _ := ret[0].(entity.SSOConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSSOConnectionMockRecorder) Get(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSSOConnection)(nil).Get), ctx, workspaceID)
}

// Save mocks base method.
func (m *MockSSOConnection) Save(ctx context.Context, workspaceID string, in entity.SSOConfigInput) (entity.SSOConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, workspaceID, in)
	ret0, _ := ret[0].(entity.SSOConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockSSOConnectionMockRecorder) Save(ctx, workspaceID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSSOConnection)(nil).Save), ctx, workspaceID, in)
}
