// Code generated by MockGen. DO NOT EDIT.
// Source: alert_monitors.go
//
// Generated by this command:
//
//	mockgen -source=alert_monitors.go -destination=./alert_monitors/alert_monitors_mock.go -package=alert_monitors
//

// Package alert_monitors is a generated GoMock package.
package alert_monitors

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertMonitors is a mock of AlertMonitors interface.
type MockAlertMonitors struct {
	ctrl     *gomock.Controller
	recorder *MockAlertMonitorsMockRecorder
	isgomock struct{}
}

// MockAlertMonitorsMockRecorder is the mock recorder for MockAlertMonitors.
type MockAlertMonitorsMockRecorder struct {
	mock *MockAlertMonitors
}

// NewMockAlertMonitors creates a new mock instance.
func NewMockAlertMonitors(ctrl *gomock.Controller) *MockAlertMonitors {
	mock := &MockAlertMonitors{ctrl: ctrl}
	mock.recorder = &MockAlertMonitorsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertMonitors) EXPECT() *MockAlertMonitorsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlertMonitors) Create(ctx context.Context, workspaceSlug string, in entity.NewAlertMonitor) (entity.AlertMonitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceSlug, in)
	ret0, _ := ret[0].(entity.AlertMonitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlertMonitorsMockRecorder) Create(ctx, workspaceSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertMonitors)(nil).Create), ctx, workspaceSlug, in)
}

// Delete mocks base method.
func (m *MockAlertMonitors) Delete(ctx context.Context, workspaceSlug, monitorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, workspaceSlug, monitorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlertMonitorsMockRecorder) Delete(ctx, workspaceSlug, monitorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertMonitors)(nil).Delete), ctx, workspaceSlug, monitorID)
}

// Get mocks base method.
func (m *MockAlertMonitors) Get(ctx context.Context, workspaceSlug, monitorID string) (entity.AlertMonitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, workspaceSlug, monitorID)
	ret0, _ := ret[0].(entity.AlertMonitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlertMonitorsMockRecorder) Get(ctx, workspaceSlug, monitorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlertMonitors)(nil).Get), ctx, workspaceSlug, monitorID)
}

// List mocks base method.
func (m *MockAlertMonitors) List(ctx context.Context, workspaceSlug string) ([]entity.AlertMonitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceSlug)
	ret0, _ := ret[0].([]entity.AlertMonitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAlertMonitorsMockRecorder) List(ctx, workspaceSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertMonitors)(nil).List), ctx, workspaceSlug)
}

// Update mocks base method.
func (m *MockAlertMonitors) Update(ctx context.Context, workspaceSlug, monitorID string, in entity.AlertMonitorUpdate) (entity.AlertMonitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, workspaceSlug, monitorID, in)
	ret0, _ := ret[0].(entity.AlertMonitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlertMonitorsMockRecorder) Update(ctx, workspaceSlug, monitorID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertMonitors)(nil).Update), ctx, workspaceSlug, monitorID, in)
}
