// Code generated by MockGen. DO NOT EDIT.
// Source: ntfy.go
//
// Generated by this command:
//
//	mockgen -source=ntfy.go -destination=./ntfy/ntfy_mock.go -package=ntfy
//

// Package ntfy is a generated GoMock package.
package ntfy

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNtfy is a mock of Ntfy interface.
type MockNtfy struct {
	ctrl     *gomock.Controller
	recorder *MockNtfyMockRecorder
	isgomock struct{}
}

// MockNtfyMockRecorder is the mock recorder for MockNtfy.
type MockNtfyMockRecorder struct {
	mock *MockNtfy
}

// NewMockNtfy creates a new mock instance.
func NewMockNtfy(ctrl *gomock.Controller) *MockNtfy {
	mock := &MockNtfy{ctrl: ctrl}
	mock.recorder = &MockNtfyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNtfy) EXPECT() *MockNtfyMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockNtfy) Publish(ctx context.Context, msg entity.NtfyMessage) (entity.NotifyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, msg)
	ret0, _ := ret[0].(entity.NotifyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockNtfyMockRecorder) Publish(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNtfy)(nil).Publish), ctx, msg)
}
