// Code generated by MockGen. DO NOT EDIT.
// Source: chat_oauth_state.go
//
// Generated by this command:
//
//	mockgen -source=chat_oauth_state.go -destination=./chat_oauth_state/chat_oauth_state_mock.go -package=chat_oauth_state
//

// Package chat_oauth_state is a generated GoMock package.
package chat_oauth_state

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChatOAuthState is a mock of ChatOAuthState interface.
type MockChatOAuthState struct {
	ctrl     *gomock.Controller
	recorder *MockChatOAuthStateMockRecorder
	isgomock struct{}
}

// MockChatOAuthStateMockRecorder is the mock recorder for MockChatOAuthState.
type MockChatOAuthStateMockRecorder struct {
	mock *MockChatOAuthState
}

// NewMockChatOAuthState creates a new mock instance.
func NewMockChatOAuthState(ctrl *gomock.Controller) *MockChatOAuthState {
	mock := &MockChatOAuthState{ctrl: ctrl}
	mock.recorder = &MockChatOAuthStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatOAuthState) EXPECT() *MockChatOAuthStateMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockChatOAuthState) Consume(ctx context.Context, state string) (entity.ChatOAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, state)
	ret0, _ := ret[0].(entity.ChatOAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockChatOAuthStateMockRecorder) Consume(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockChatOAuthState)(nil).Consume), ctx, state)
}

// Store mocks base method.
func (m *MockChatOAuthState) Store(ctx context.Context, state string, data entity.ChatOAuthState, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, state, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockChatOAuthStateMockRecorder) Store(ctx, state, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockChatOAuthState)(nil).Store), ctx, state, data, ttl)
}
