// Code generated by MockGen. DO NOT EDIT.
// Source: member.go
//
// Generated by this command:
//
//	mockgen -source=member.go -destination=./member/member_mock.go -package=member
//

// Package member is a generated GoMock package.
package member

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMember is a mock of Member interface.
type MockMember struct {
	ctrl     *gomock.Controller
	recorder *MockMemberMockRecorder
	isgomock struct{}
}

// MockMemberMockRecorder is the mock recorder for MockMember.
type MockMemberMockRecorder struct {
	mock *MockMember
}

// NewMockMember creates a new mock instance.
func NewMockMember(ctrl *gomock.Controller) *MockMember {
	mock := &MockMember{ctrl: ctrl}
	mock.recorder = &MockMemberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMember) EXPECT() *MockMemberMockRecorder {
	return m.recorder
}

// CountOtherActive mocks base method.
func (m *MockMember) CountOtherActive(ctx context.Context, userID, exceptWorkspaceID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOtherActive", ctx, userID, exceptWorkspaceID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOtherActive indicates an expected call of CountOtherActive.
func (mr *MockMemberMockRecorder) CountOtherActive(ctx, userID, exceptWorkspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOtherActive", reflect.TypeOf((*MockMember)(nil).CountOtherActive), ctx, userID, exceptWorkspaceID)
}

// Create mocks base method.
func (m *MockMember) Create(ctx context.Context, workspaceID, userID string, status entity.MemberStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceID, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMemberMockRecorder) Create(ctx, workspaceID, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMember)(nil).Create), ctx, workspaceID, userID, status)
}

// DeleteInvited mocks base method.
func (m *MockMember) DeleteInvited(ctx context.Context, workspaceID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvited", ctx, workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvited indicates an expected call of DeleteInvited.
func (mr *MockMemberMockRecorder) DeleteInvited(ctx, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvited", reflect.TypeOf((*MockMember)(nil).DeleteInvited), ctx, workspaceID, userID)
}

// Get mocks base method.
func (m *MockMember) Get(ctx context.Context, workspaceID, userID string) (entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, workspaceID, userID)
	ret0, _ := ret[0].(entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMemberMockRecorder) Get(ctx, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMember)(nil).Get), ctx, workspaceID, userID)
}

// IsActive mocks base method.
func (m *MockMember) IsActive(ctx context.Context, workspaceID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive", ctx, workspaceID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsActive indicates an expected call of IsActive.
func (mr *MockMemberMockRecorder) IsActive(ctx, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockMember)(nil).IsActive), ctx, workspaceID, userID)
}

// ListByWorkspace mocks base method.
func (m *MockMember) ListByWorkspace(ctx context.Context, workspaceID string) ([]entity.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByWorkspace indicates an expected call of ListByWorkspace.
func (mr *MockMemberMockRecorder) ListByWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByWorkspace", reflect.TypeOf((*MockMember)(nil).ListByWorkspace), ctx, workspaceID)
}

// UpdateStatus mocks base method.
func (m *MockMember) UpdateStatus(ctx context.Context, workspaceID, userID string, status entity.MemberStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, workspaceID, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockMemberMockRecorder) UpdateStatus(ctx, workspaceID, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockMember)(nil).UpdateStatus), ctx, workspaceID, userID, status)
}
