// Code generated by MockGen. DO NOT EDIT.
// Source: chats.go
//
// Generated by this command:
//
//	mockgen -source=chats.go -destination=./chats/chats_mock.go -package=chats
//

// Package chats is a generated GoMock package.
package chats

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChats is a mock of Chats interface.
type MockChats struct {
	ctrl     *gomock.Controller
	recorder *MockChatsMockRecorder
	isgomock struct{}
}

// MockChatsMockRecorder is the mock recorder for MockChats.
type MockChatsMockRecorder struct {
	mock *MockChats
}

// NewMockChats creates a new mock instance.
func NewMockChats(ctrl *gomock.Controller) *MockChats {
	mock := &MockChats{ctrl: ctrl}
	mock.recorder = &MockChatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChats) EXPECT() *MockChatsMockRecorder {
	return m.recorder
}

// CompleteIdentityOAuth mocks base method.
func (m *MockChats) CompleteIdentityOAuth(ctx context.Context, provider entity.ChatProvider, code, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteIdentityOAuth", ctx, provider, code, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteIdentityOAuth indicates an expected call of CompleteIdentityOAuth.
func (mr *MockChatsMockRecorder) CompleteIdentityOAuth(ctx, provider, code, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteIdentityOAuth", reflect.TypeOf((*MockChats)(nil).CompleteIdentityOAuth), ctx, provider, code, state)
}

// CompleteOAuth mocks base method.
func (m *MockChats) CompleteOAuth(ctx context.Context, provider entity.ChatProvider, code, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteOAuth", ctx, provider, code, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteOAuth indicates an expected call of CompleteOAuth.
func (mr *MockChatsMockRecorder) CompleteOAuth(ctx, provider, code, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteOAuth", reflect.TypeOf((*MockChats)(nil).CompleteOAuth), ctx, provider, code, state)
}

// Connect mocks base method.
func (m *MockChats) Connect(ctx context.Context, workspaceSlug string, in entity.ChatConnectInput) (entity.ChatConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, workspaceSlug, in)
	ret0, _ := ret[0].(entity.ChatConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockChatsMockRecorder) Connect(ctx, workspaceSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockChats)(nil).Connect), ctx, workspaceSlug, in)
}

// Delete mocks base method.
func (m *MockChats) Delete(ctx context.Context, workspaceSlug string, provider entity.ChatProvider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, workspaceSlug, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChatsMockRecorder) Delete(ctx, workspaceSlug, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChats)(nil).Delete), ctx, workspaceSlug, provider)
}

// LinkIdentity mocks base method.
func (m *MockChats) LinkIdentity(ctx context.Context, workspaceSlug string, provider entity.ChatProvider) (entity.ChatIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkIdentity", ctx, workspaceSlug, provider)
	ret0, _ := ret[0].(entity.ChatIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkIdentity indicates an expected call of LinkIdentity.
func (mr *MockChatsMockRecorder) LinkIdentity(ctx, workspaceSlug, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkIdentity", reflect.TypeOf((*MockChats)(nil).LinkIdentity), ctx, workspaceSlug, provider)
}

// List mocks base method.
func (m *MockChats) List(ctx context.Context, workspaceSlug string) ([]entity.ChatConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceSlug)
	ret0, _ := ret[0].([]entity.ChatConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockChatsMockRecorder) List(ctx, workspaceSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockChats)(nil).List), ctx, workspaceSlug)
}

// SetDefaults mocks base method.
func (m *MockChats) SetDefaults(ctx context.Context, workspaceSlug string, provider entity.ChatProvider, namingPattern, announceChannel string, archiveOnResolve bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaults", ctx, workspaceSlug, provider, namingPattern, announceChannel, archiveOnResolve)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaults indicates an expected call of SetDefaults.
func (mr *MockChatsMockRecorder) SetDefaults(ctx, workspaceSlug, provider, namingPattern, announceChannel, archiveOnResolve any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaults", reflect.TypeOf((*MockChats)(nil).SetDefaults), ctx, workspaceSlug, provider, namingPattern, announceChannel, archiveOnResolve)
}

// StartIdentityOAuth mocks base method.
func (m *MockChats) StartIdentityOAuth(ctx context.Context, workspaceSlug string, provider entity.ChatProvider) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartIdentityOAuth", ctx, workspaceSlug, provider)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartIdentityOAuth indicates an expected call of StartIdentityOAuth.
func (mr *MockChatsMockRecorder) StartIdentityOAuth(ctx, workspaceSlug, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartIdentityOAuth", reflect.TypeOf((*MockChats)(nil).StartIdentityOAuth), ctx, workspaceSlug, provider)
}

// StartOAuth mocks base method.
func (m *MockChats) StartOAuth(ctx context.Context, workspaceSlug string, provider entity.ChatProvider) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartOAuth", ctx, workspaceSlug, provider)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartOAuth indicates an expected call of StartOAuth.
func (mr *MockChatsMockRecorder) StartOAuth(ctx, workspaceSlug, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartOAuth", reflect.TypeOf((*MockChats)(nil).StartOAuth), ctx, workspaceSlug, provider)
}

// TestConnection mocks base method.
func (m *MockChats) TestConnection(ctx context.Context, workspaceSlug string, provider entity.ChatProvider) (entity.ChatSendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestConnection", ctx, workspaceSlug, provider)
	ret0, _ := ret[0].(entity.ChatSendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestConnection indicates an expected call of TestConnection.
func (mr *MockChatsMockRecorder) TestConnection(ctx, workspaceSlug, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestConnection", reflect.TypeOf((*MockChats)(nil).TestConnection), ctx, workspaceSlug, provider)
}
