// Code generated by MockGen. DO NOT EDIT.
// Source: alert_route.go
//
// Generated by this command:
//
//	mockgen -source=alert_route.go -destination=./alert_route/alert_route_mock.go -package=alert_route
//

// Package alert_route is a generated GoMock package.
package alert_route

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertRoute is a mock of AlertRoute interface.
type MockAlertRoute struct {
	ctrl     *gomock.Controller
	recorder *MockAlertRouteMockRecorder
	isgomock struct{}
}

// MockAlertRouteMockRecorder is the mock recorder for MockAlertRoute.
type MockAlertRouteMockRecorder struct {
	mock *MockAlertRoute
}

// NewMockAlertRoute creates a new mock instance.
func NewMockAlertRoute(ctrl *gomock.Controller) *MockAlertRoute {
	mock := &MockAlertRoute{ctrl: ctrl}
	mock.recorder = &MockAlertRouteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertRoute) EXPECT() *MockAlertRouteMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlertRoute) Create(ctx context.Context, workspaceID string, in entity.NewAlertRoute) (entity.AlertRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceID, in)
	ret0, _ := ret[0].(entity.AlertRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlertRouteMockRecorder) Create(ctx, workspaceID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertRoute)(nil).Create), ctx, workspaceID, in)
}

// Delete mocks base method.
func (m *MockAlertRoute) Delete(ctx context.Context, workspaceID, routeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, workspaceID, routeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlertRouteMockRecorder) Delete(ctx, workspaceID, routeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertRoute)(nil).Delete), ctx, workspaceID, routeID)
}

// List mocks base method.
func (m *MockAlertRoute) List(ctx context.Context, workspaceID string) ([]entity.AlertRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.AlertRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAlertRouteMockRecorder) List(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertRoute)(nil).List), ctx, workspaceID)
}

// ListGroupRules mocks base method.
func (m *MockAlertRoute) ListGroupRules(ctx context.Context, workspaceID string) ([]entity.GroupRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupRules", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.GroupRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupRules indicates an expected call of ListGroupRules.
func (mr *MockAlertRouteMockRecorder) ListGroupRules(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupRules", reflect.TypeOf((*MockAlertRoute)(nil).ListGroupRules), ctx, workspaceID)
}

// Reorder mocks base method.
func (m *MockAlertRoute) Reorder(ctx context.Context, workspaceID string, orderedIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reorder", ctx, workspaceID, orderedIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reorder indicates an expected call of Reorder.
func (mr *MockAlertRouteMockRecorder) Reorder(ctx, workspaceID, orderedIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reorder", reflect.TypeOf((*MockAlertRoute)(nil).Reorder), ctx, workspaceID, orderedIDs)
}

// ReplaceGroupRules mocks base method.
func (m *MockAlertRoute) ReplaceGroupRules(ctx context.Context, workspaceID string, rules []entity.GroupRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceGroupRules", ctx, workspaceID, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceGroupRules indicates an expected call of ReplaceGroupRules.
func (mr *MockAlertRouteMockRecorder) ReplaceGroupRules(ctx, workspaceID, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceGroupRules", reflect.TypeOf((*MockAlertRoute)(nil).ReplaceGroupRules), ctx, workspaceID, rules)
}

// SetDefaultPolicy mocks base method.
func (m *MockAlertRoute) SetDefaultPolicy(ctx context.Context, workspaceID, policyRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultPolicy", ctx, workspaceID, policyRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultPolicy indicates an expected call of SetDefaultPolicy.
func (mr *MockAlertRouteMockRecorder) SetDefaultPolicy(ctx, workspaceID, policyRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultPolicy", reflect.TypeOf((*MockAlertRoute)(nil).SetDefaultPolicy), ctx, workspaceID, policyRef)
}

// Settings mocks base method.
func (m *MockAlertRoute) Settings(ctx context.Context, workspaceID string) (entity.AlertSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Settings", ctx, workspaceID)
	ret0, _ := ret[0].(entity.AlertSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Settings indicates an expected call of Settings.
func (mr *MockAlertRouteMockRecorder) Settings(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Settings", reflect.TypeOf((*MockAlertRoute)(nil).Settings), ctx, workspaceID)
}

// Update mocks base method.
func (m *MockAlertRoute) Update(ctx context.Context, workspaceID, routeID string, in entity.NewAlertRoute) (entity.AlertRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, workspaceID, routeID, in)
	ret0, _ := ret[0].(entity.AlertRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlertRouteMockRecorder) Update(ctx, workspaceID, routeID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertRoute)(nil).Update), ctx, workspaceID, routeID, in)
}
