// Code generated by MockGen. DO NOT EDIT.
// Source: alert_source.go
//
// Generated by this command:
//
//	mockgen -source=alert_source.go -destination=./alert_source/alert_source_mock.go -package=alert_source
//

// Package alert_source is a generated GoMock package.
package alert_source

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertSource is a mock of AlertSource interface.
type MockAlertSource struct {
	ctrl     *gomock.Controller
	recorder *MockAlertSourceMockRecorder
	isgomock struct{}
}

// MockAlertSourceMockRecorder is the mock recorder for MockAlertSource.
type MockAlertSourceMockRecorder struct {
	mock *MockAlertSource
}

// NewMockAlertSource creates a new mock instance.
func NewMockAlertSource(ctrl *gomock.Controller) *MockAlertSource {
	mock := &MockAlertSource{ctrl: ctrl}
	mock.recorder = &MockAlertSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertSource) EXPECT() *MockAlertSourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlertSource) Create(ctx context.Context, workspaceID string, src entity.AlertSource) (entity.AlertSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceID, src)
	ret0, _ := ret[0].(entity.AlertSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAlertSourceMockRecorder) Create(ctx, workspaceID, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertSource)(nil).Create), ctx, workspaceID, src)
}

// Delete mocks base method.
func (m *MockAlertSource) Delete(ctx context.Context, workspaceID, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, workspaceID, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlertSourceMockRecorder) Delete(ctx, workspaceID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertSource)(nil).Delete), ctx, workspaceID, slug)
}

// GetBySlug mocks base method.
func (m *MockAlertSource) GetBySlug(ctx context.Context, workspaceID, slug string) (entity.AlertSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, workspaceID, slug)
	ret0, _ := ret[0].(entity.AlertSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockAlertSourceMockRecorder) GetBySlug(ctx, workspaceID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockAlertSource)(nil).GetBySlug), ctx, workspaceID, slug)
}

// GetByToken mocks base method.
func (m *MockAlertSource) GetByToken(ctx context.Context, token string) (entity.AlertSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(entity.AlertSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockAlertSourceMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockAlertSource)(nil).GetByToken), ctx, token)
}

// ListByWorkspace mocks base method.
func (m *MockAlertSource) ListByWorkspace(ctx context.Context, workspaceID string) ([]entity.AlertSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByWorkspace", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.AlertSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByWorkspace indicates an expected call of ListByWorkspace.
func (mr *MockAlertSourceMockRecorder) ListByWorkspace(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByWorkspace", reflect.TypeOf((*MockAlertSource)(nil).ListByWorkspace), ctx, workspaceID)
}

// MarkDelivery mocks base method.
func (m *MockAlertSource) MarkDelivery(ctx context.Context, sourceID string, at time.Time, failed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelivery", ctx, sourceID, at, failed)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDelivery indicates an expected call of MarkDelivery.
func (mr *MockAlertSourceMockRecorder) MarkDelivery(ctx, sourceID, at, failed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelivery", reflect.TypeOf((*MockAlertSource)(nil).MarkDelivery), ctx, sourceID, at, failed)
}

// ReplaceMappings mocks base method.
func (m *MockAlertSource) ReplaceMappings(ctx context.Context, sourceID string, mappings []entity.SourceMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceMappings", ctx, sourceID, mappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceMappings indicates an expected call of ReplaceMappings.
func (mr *MockAlertSourceMockRecorder) ReplaceMappings(ctx, sourceID, mappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceMappings", reflect.TypeOf((*MockAlertSource)(nil).ReplaceMappings), ctx, sourceID, mappings)
}

// RotateSecret mocks base method.
func (m *MockAlertSource) RotateSecret(ctx context.Context, workspaceID, slug, secret string) (entity.AlertSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSecret", ctx, workspaceID, slug, secret)
	ret0, _ := ret[0].(entity.AlertSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateSecret indicates an expected call of RotateSecret.
func (mr *MockAlertSourceMockRecorder) RotateSecret(ctx, workspaceID, slug, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSecret", reflect.TypeOf((*MockAlertSource)(nil).RotateSecret), ctx, workspaceID, slug, secret)
}

// SetPaused mocks base method.
func (m *MockAlertSource) SetPaused(ctx context.Context, workspaceID, slug string, paused bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPaused", ctx, workspaceID, slug, paused)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPaused indicates an expected call of SetPaused.
func (mr *MockAlertSourceMockRecorder) SetPaused(ctx, workspaceID, slug, paused any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPaused", reflect.TypeOf((*MockAlertSource)(nil).SetPaused), ctx, workspaceID, slug, paused)
}

// Update mocks base method.
func (m *MockAlertSource) Update(ctx context.Context, workspaceID, slug string, in entity.AlertSourceUpdate) (entity.AlertSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, workspaceID, slug, in)
	ret0, _ := ret[0].(entity.AlertSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlertSourceMockRecorder) Update(ctx, workspaceID, slug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertSource)(nil).Update), ctx, workspaceID, slug, in)
}
