// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -source=notifier.go -destination=./notifier/notifier_mock.go -package=notifier
//

// Package notifier is a generated GoMock package.
package notifier

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// CallWebhook mocks base method.
func (m *MockNotifier) CallWebhook(ctx context.Context, hook entity.EscalationWebhook, alert entity.Alert, page entity.AlertPage) entity.NotifyResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallWebhook", ctx, hook, alert, page)
	ret0, _ := ret[0].(entity.NotifyResult)
	return ret0
}

// CallWebhook indicates an expected call of CallWebhook.
func (mr *MockNotifierMockRecorder) CallWebhook(ctx, hook, alert, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallWebhook", reflect.TypeOf((*MockNotifier)(nil).CallWebhook), ctx, hook, alert, page)
}

// PageUser mocks base method.
func (m *MockNotifier) PageUser(ctx context.Context, member entity.Member, page entity.AlertPage) entity.NotifyResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PageUser", ctx, member, page)
	ret0, _ := ret[0].(entity.NotifyResult)
	return ret0
}

// PageUser indicates an expected call of PageUser.
func (mr *MockNotifierMockRecorder) PageUser(ctx, member, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PageUser", reflect.TypeOf((*MockNotifier)(nil).PageUser), ctx, member, page)
}
