// Code generated by MockGen. DO NOT EDIT.
// Source: channel_verification.go
//
// Generated by this command:
//
//	mockgen -source=channel_verification.go -destination=./channel_verification/channel_verification_mock.go -package=channel_verification
//

// Package channel_verification is a generated GoMock package.
package channel_verification

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelVerification is a mock of ChannelVerification interface.
type MockChannelVerification struct {
	ctrl     *gomock.Controller
	recorder *MockChannelVerificationMockRecorder
	isgomock struct{}
}

// MockChannelVerificationMockRecorder is the mock recorder for MockChannelVerification.
type MockChannelVerificationMockRecorder struct {
	mock *MockChannelVerification
}

// NewMockChannelVerification creates a new mock instance.
func NewMockChannelVerification(ctrl *gomock.Controller) *MockChannelVerification {
	mock := &MockChannelVerification{ctrl: ctrl}
	mock.recorder = &MockChannelVerificationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelVerification) EXPECT() *MockChannelVerificationMockRecorder {
	return m.recorder
}

// ConsumeCode mocks base method.
func (m *MockChannelVerification) ConsumeCode(ctx context.Context, channelID, userID, codeHash string, now time.Time) (entity.ChannelVerifyClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeCode", ctx, channelID, userID, codeHash, now)
	ret0, _ := ret[0].(entity.ChannelVerifyClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeCode indicates an expected call of ConsumeCode.
func (mr *MockChannelVerificationMockRecorder) ConsumeCode(ctx, channelID, userID, codeHash, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeCode", reflect.TypeOf((*MockChannelVerification)(nil).ConsumeCode), ctx, channelID, userID, codeHash, now)
}

// ConsumeToken mocks base method.
func (m *MockChannelVerification) ConsumeToken(ctx context.Context, tokenHash string, now time.Time) (entity.ChannelVerifyClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeToken", ctx, tokenHash, now)
	ret0, _ := ret[0].(entity.ChannelVerifyClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeToken indicates an expected call of ConsumeToken.
func (mr *MockChannelVerificationMockRecorder) ConsumeToken(ctx, tokenHash, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeToken", reflect.TypeOf((*MockChannelVerification)(nil).ConsumeToken), ctx, tokenHash, now)
}

// Start mocks base method.
func (m *MockChannelVerification) Start(ctx context.Context, rec entity.ChannelVerifyRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockChannelVerificationMockRecorder) Start(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChannelVerification)(nil).Start), ctx, rec)
}
