// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AlertEscalation is an object representing the database table.
type AlertEscalation struct {
	ID           string     `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID  string     `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	AlertID      string     `boil:"alert_id" json:"alert_id" toml:"alert_id" yaml:"alert_id"`
	PolicyID     string     `boil:"policy_id" json:"policy_id" toml:"policy_id" yaml:"policy_id"`
	State        string     `boil:"state" json:"state" toml:"state" yaml:"state"`
	Cycle        int        `boil:"cycle" json:"cycle" toml:"cycle" yaml:"cycle"`
	StepIndex    int        `boil:"step_index" json:"step_index" toml:"step_index" yaml:"step_index"`
	Plan         types.JSON `boil:"plan" json:"plan" toml:"plan" yaml:"plan"`
	NextAt       null.Time  `boil:"next_at" json:"next_at,omitempty" toml:"next_at" yaml:"next_at,omitempty"`
	AckedAt      null.Time  `boil:"acked_at" json:"acked_at,omitempty" toml:"acked_at" yaml:"acked_at,omitempty"`
	AckExpiresAt null.Time  `boil:"ack_expires_at" json:"ack_expires_at,omitempty" toml:"ack_expires_at" yaml:"ack_expires_at,omitempty"`
	StartedAt    time.Time  `boil:"started_at" json:"started_at" toml:"started_at" yaml:"started_at"`
	EndedAt      null.Time  `boil:"ended_at" json:"ended_at,omitempty" toml:"ended_at" yaml:"ended_at,omitempty"`
	UpdatedAt    time.Time  `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *alertEscalationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L alertEscalationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AlertEscalationColumns = struct {
	ID           string
	WorkspaceID  string
	AlertID      string
	PolicyID     string
	State        string
	Cycle        string
	StepIndex    string
	Plan         string
	NextAt       string
	AckedAt      string
	AckExpiresAt string
	StartedAt    string
	EndedAt      string
	UpdatedAt    string
}{
	ID:           "id",
	WorkspaceID:  "workspace_id",
	AlertID:      "alert_id",
	PolicyID:     "policy_id",
	State:        "state",
	Cycle:        "cycle",
	StepIndex:    "step_index",
	Plan:         "plan",
	NextAt:       "next_at",
	AckedAt:      "acked_at",
	AckExpiresAt: "ack_expires_at",
	StartedAt:    "started_at",
	EndedAt:      "ended_at",
	UpdatedAt:    "updated_at",
}

var AlertEscalationTableColumns = struct {
	ID           string
	WorkspaceID  string
	AlertID      string
	PolicyID     string
	State        string
	Cycle        string
	StepIndex    string
	Plan         string
	NextAt       string
	AckedAt      string
	AckExpiresAt string
	StartedAt    string
	EndedAt      string
	UpdatedAt    string
}{
	ID:           "alert_escalations.id",
	WorkspaceID:  "alert_escalations.workspace_id",
	AlertID:      "alert_escalations.alert_id",
	PolicyID:     "alert_escalations.policy_id",
	State:        "alert_escalations.state",
	Cycle:        "alert_escalations.cycle",
	StepIndex:    "alert_escalations.step_index",
	Plan:         "alert_escalations.plan",
	NextAt:       "alert_escalations.next_at",
	AckedAt:      "alert_escalations.acked_at",
	AckExpiresAt: "alert_escalations.ack_expires_at",
	StartedAt:    "alert_escalations.started_at",
	EndedAt:      "alert_escalations.ended_at",
	UpdatedAt:    "alert_escalations.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AlertEscalationWhere = struct {
	ID           whereHelperstring
	WorkspaceID  whereHelperstring
	AlertID      whereHelperstring
	PolicyID     whereHelperstring
	State        whereHelperstring
	Cycle        whereHelperint
	StepIndex    whereHelperint
	Plan         whereHelpertypes_JSON
	NextAt       whereHelpernull_Time
	AckedAt      whereHelpernull_Time
	AckExpiresAt whereHelpernull_Time
	StartedAt    whereHelpertime_Time
	EndedAt      whereHelpernull_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperstring{field: "\"alert_escalations\".\"id\""},
	WorkspaceID:  whereHelperstring{field: "\"alert_escalations\".\"workspace_id\""},
	AlertID:      whereHelperstring{field: "\"alert_escalations\".\"alert_id\""},
	PolicyID:     whereHelperstring{field: "\"alert_escalations\".\"policy_id\""},
	State:        whereHelperstring{field: "\"alert_escalations\".\"state\""},
	Cycle:        whereHelperint{field: "\"alert_escalations\".\"cycle\""},
	StepIndex:    whereHelperint{field: "\"alert_escalations\".\"step_index\""},
	Plan:         whereHelpertypes_JSON{field: "\"alert_escalations\".\"plan\""},
	NextAt:       whereHelpernull_Time{field: "\"alert_escalations\".\"next_at\""},
	AckedAt:      whereHelpernull_Time{field: "\"alert_escalations\".\"acked_at\""},
	AckExpiresAt: whereHelpernull_Time{field: "\"alert_escalations\".\"ack_expires_at\""},
	StartedAt:    whereHelpertime_Time{field: "\"alert_escalations\".\"started_at\""},
	EndedAt:      whereHelpernull_Time{field: "\"alert_escalations\".\"ended_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"alert_escalations\".\"updated_at\""},
}

// AlertEscalationRels is where relationship names are stored.
var AlertEscalationRels = struct {
	Alert     string
	Policy    string
	Workspace string
}{
	Alert:     "Alert",
	Policy:    "Policy",
	Workspace: "Workspace",
}

// alertEscalationR is where relationships are stored.
type alertEscalationR struct {
	Alert     *Alert            `boil:"Alert" json:"Alert" toml:"Alert" yaml:"Alert"`
	Policy    *EscalationPolicy `boil:"Policy" json:"Policy" toml:"Policy" yaml:"Policy"`
	Workspace *Workspace        `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
}

// NewStruct creates a new relationship struct
func (*alertEscalationR) NewStruct() *alertEscalationR {
	return &alertEscalationR{}
}

func (o *AlertEscalation) GetAlert() *Alert {
	if o == nil {
		return nil
	}

	return o.R.GetAlert()
}

func (r *alertEscalationR) GetAlert() *Alert {
	if r == nil {
		return nil
	}

	return r.Alert
}

func (o *AlertEscalation) GetPolicy() *EscalationPolicy {
	if o == nil {
		return nil
	}

	return o.R.GetPolicy()
}

func (r *alertEscalationR) GetPolicy() *EscalationPolicy {
	if r == nil {
		return nil
	}

	return r.Policy
}

func (o *AlertEscalation) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *alertEscalationR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

// alertEscalationL is where Load methods for each relationship are stored.
type alertEscalationL struct{}

var (
	alertEscalationAllColumns            = []string{"id", "workspace_id", "alert_id", "policy_id", "state", "cycle", "step_index", "plan", "next_at", "acked_at", "ack_expires_at", "started_at", "ended_at", "updated_at"}
	alertEscalationColumnsWithoutDefault = []string{"workspace_id", "alert_id", "policy_id", "plan"}
	alertEscalationColumnsWithDefault    = []string{"id", "state", "cycle", "step_index", "next_at", "acked_at", "ack_expires_at", "started_at", "ended_at", "updated_at"}
	alertEscalationPrimaryKeyColumns     = []string{"id"}
	alertEscalationGeneratedColumns      = []string{}
)

type (
	// AlertEscalationSlice is an alias for a slice of pointers to AlertEscalation.
	// This should almost always be used instead of []AlertEscalation.
	AlertEscalationSlice []*AlertEscalation
	// AlertEscalationHook is the signature for custom AlertEscalation hook methods
	AlertEscalationHook func(context.Context, boil.ContextExecutor, *AlertEscalation) error

	alertEscalationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	alertEscalationType                 = reflect.TypeOf(&AlertEscalation{})
	alertEscalationMapping              = queries.MakeStructMapping(alertEscalationType)
	alertEscalationPrimaryKeyMapping, _ = queries.BindMapping(alertEscalationType, alertEscalationMapping, alertEscalationPrimaryKeyColumns)
	alertEscalationInsertCacheMut       sync.RWMutex
	alertEscalationInsertCache          = make(map[string]insertCache)
	alertEscalationUpdateCacheMut       sync.RWMutex
	alertEscalationUpdateCache          = make(map[string]updateCache)
	alertEscalationUpsertCacheMut       sync.RWMutex
	alertEscalationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var alertEscalationAfterSelectMu sync.Mutex
var alertEscalationAfterSelectHooks []AlertEscalationHook

var alertEscalationBeforeInsertMu sync.Mutex
var alertEscalationBeforeInsertHooks []AlertEscalationHook
var alertEscalationAfterInsertMu sync.Mutex
var alertEscalationAfterInsertHooks []AlertEscalationHook

var alertEscalationBeforeUpdateMu sync.Mutex
var alertEscalationBeforeUpdateHooks []AlertEscalationHook
var alertEscalationAfterUpdateMu sync.Mutex
var alertEscalationAfterUpdateHooks []AlertEscalationHook

var alertEscalationBeforeDeleteMu sync.Mutex
var alertEscalationBeforeDeleteHooks []AlertEscalationHook
var alertEscalationAfterDeleteMu sync.Mutex
var alertEscalationAfterDeleteHooks []AlertEscalationHook

var alertEscalationBeforeUpsertMu sync.Mutex
var alertEscalationBeforeUpsertHooks []AlertEscalationHook
var alertEscalationAfterUpsertMu sync.Mutex
var alertEscalationAfterUpsertHooks []AlertEscalationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AlertEscalation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AlertEscalation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AlertEscalation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AlertEscalation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AlertEscalation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AlertEscalation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AlertEscalation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AlertEscalation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AlertEscalation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertEscalationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAlertEscalationHook registers your hook function for all future operations.
func AddAlertEscalationHook(hookPoint boil.HookPoint, alertEscalationHook AlertEscalationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		alertEscalationAfterSelectMu.Lock()
		alertEscalationAfterSelectHooks = append(alertEscalationAfterSelectHooks, alertEscalationHook)
		alertEscalationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		alertEscalationBeforeInsertMu.Lock()
		alertEscalationBeforeInsertHooks = append(alertEscalationBeforeInsertHooks, alertEscalationHook)
		alertEscalationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		alertEscalationAfterInsertMu.Lock()
		alertEscalationAfterInsertHooks = append(alertEscalationAfterInsertHooks, alertEscalationHook)
		alertEscalationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		alertEscalationBeforeUpdateMu.Lock()
		alertEscalationBeforeUpdateHooks = append(alertEscalationBeforeUpdateHooks, alertEscalationHook)
		alertEscalationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		alertEscalationAfterUpdateMu.Lock()
		alertEscalationAfterUpdateHooks = append(alertEscalationAfterUpdateHooks, alertEscalationHook)
		alertEscalationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		alertEscalationBeforeDeleteMu.Lock()
		alertEscalationBeforeDeleteHooks = append(alertEscalationBeforeDeleteHooks, alertEscalationHook)
		alertEscalationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		alertEscalationAfterDeleteMu.Lock()
		alertEscalationAfterDeleteHooks = append(alertEscalationAfterDeleteHooks, alertEscalationHook)
		alertEscalationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		alertEscalationBeforeUpsertMu.Lock()
		alertEscalationBeforeUpsertHooks = append(alertEscalationBeforeUpsertHooks, alertEscalationHook)
		alertEscalationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		alertEscalationAfterUpsertMu.Lock()
		alertEscalationAfterUpsertHooks = append(alertEscalationAfterUpsertHooks, alertEscalationHook)
		alertEscalationAfterUpsertMu.Unlock()
	}
}

// One returns a single alertEscalation record from the query.
func (q alertEscalationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AlertEscalation, error) {
	o := &AlertEscalation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for alert_escalations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AlertEscalation records from the query.
func (q alertEscalationQuery) All(ctx context.Context, exec boil.ContextExecutor) (AlertEscalationSlice, error) {
	var o []*AlertEscalation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to AlertEscalation slice")
	}

	if len(alertEscalationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AlertEscalation records in the query.
func (q alertEscalationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count alert_escalations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q alertEscalationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if alert_escalations exists")
	}

	return count > 0, nil
}

// Alert pointed to by the foreign key.
func (o *AlertEscalation) Alert(mods ...qm.QueryMod) alertQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AlertID),
	}

	queryMods = append(queryMods, mods...)

	return Alerts(queryMods...)
}

// Policy pointed to by the foreign key.
func (o *AlertEscalation) Policy(mods ...qm.QueryMod) escalationPolicyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PolicyID),
	}

	queryMods = append(queryMods, mods...)

	return EscalationPolicies(queryMods...)
}

// Workspace pointed to by the foreign key.
func (o *AlertEscalation) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// LoadAlert allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (alertEscalationL) LoadAlert(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertEscalation any, mods queries.Applicator) error {
	var slice []*AlertEscalation
	var object *AlertEscalation

	if singular {
		var ok bool
		object, ok = maybeAlertEscalation.(*AlertEscalation)
		if !ok {
			object = new(AlertEscalation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertEscalation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertEscalation))
			}
		}
	} else {
		s, ok := maybeAlertEscalation.(*[]*AlertEscalation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertEscalation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertEscalation))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertEscalationR{}
		}
		args[object.AlertID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertEscalationR{}
			}

			args[obj.AlertID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`alerts`),
		qm.WhereIn(`alerts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Alert")
	}

	var resultSlice []*Alert
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Alert")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for alerts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for alerts")
	}

	if len(alertAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Alert = foreign
		if foreign.R == nil {
			foreign.R = &alertR{}
		}
		foreign.R.AlertEscalation = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AlertID == foreign.ID {
				local.R.Alert = foreign
				if foreign.R == nil {
					foreign.R = &alertR{}
				}
				foreign.R.AlertEscalation = local
				break
			}
		}
	}

	return nil
}

// LoadPolicy allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (alertEscalationL) LoadPolicy(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertEscalation any, mods queries.Applicator) error {
	var slice []*AlertEscalation
	var object *AlertEscalation

	if singular {
		var ok bool
		object, ok = maybeAlertEscalation.(*AlertEscalation)
		if !ok {
			object = new(AlertEscalation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertEscalation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertEscalation))
			}
		}
	} else {
		s, ok := maybeAlertEscalation.(*[]*AlertEscalation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertEscalation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertEscalation))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertEscalationR{}
		}
		args[object.PolicyID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertEscalationR{}
			}

			args[obj.PolicyID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`escalation_policies`),
		qm.WhereIn(`escalation_policies.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load EscalationPolicy")
	}

	var resultSlice []*EscalationPolicy
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice EscalationPolicy")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for escalation_policies")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for escalation_policies")
	}

	if len(escalationPolicyAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Policy = foreign
		if foreign.R == nil {
			foreign.R = &escalationPolicyR{}
		}
		foreign.R.PolicyAlertEscalations = append(foreign.R.PolicyAlertEscalations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PolicyID == foreign.ID {
				local.R.Policy = foreign
				if foreign.R == nil {
					foreign.R = &escalationPolicyR{}
				}
				foreign.R.PolicyAlertEscalations = append(foreign.R.PolicyAlertEscalations, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (alertEscalationL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertEscalation any, mods queries.Applicator) error {
	var slice []*AlertEscalation
	var object *AlertEscalation

	if singular {
		var ok bool
		object, ok = maybeAlertEscalation.(*AlertEscalation)
		if !ok {
			object = new(AlertEscalation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertEscalation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertEscalation))
			}
		}
	} else {
		s, ok := maybeAlertEscalation.(*[]*AlertEscalation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertEscalation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertEscalation))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertEscalationR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertEscalationR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.AlertEscalations = append(foreign.R.AlertEscalations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.AlertEscalations = append(foreign.R.AlertEscalations, local)
				break
			}
		}
	}

	return nil
}

// SetAlert of the alertEscalation to the related item.
// Sets o.R.Alert to related.
// Adds o to related.R.AlertEscalation.
func (o *AlertEscalation) SetAlert(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Alert) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alert_escalations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"alert_id"}),
		strmangle.WhereClause("\"", "\"", 2, alertEscalationPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AlertID = related.ID
	if o.R == nil {
		o.R = &alertEscalationR{
			Alert: related,
		}
	} else {
		o.R.Alert = related
	}

	if related.R == nil {
		related.R = &alertR{
			AlertEscalation: o,
		}
	} else {
		related.R.AlertEscalation = o
	}

	return nil
}

// SetPolicy of the alertEscalation to the related item.
// Sets o.R.Policy to related.
// Adds o to related.R.PolicyAlertEscalations.
func (o *AlertEscalation) SetPolicy(ctx context.Context, exec boil.ContextExecutor, insert bool, related *EscalationPolicy) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alert_escalations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"policy_id"}),
		strmangle.WhereClause("\"", "\"", 2, alertEscalationPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PolicyID = related.ID
	if o.R == nil {
		o.R = &alertEscalationR{
			Policy: related,
		}
	} else {
		o.R.Policy = related
	}

	if related.R == nil {
		related.R = &escalationPolicyR{
			PolicyAlertEscalations: AlertEscalationSlice{o},
		}
	} else {
		related.R.PolicyAlertEscalations = append(related.R.PolicyAlertEscalations, o)
	}

	return nil
}

// SetWorkspace of the alertEscalation to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.AlertEscalations.
func (o *AlertEscalation) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alert_escalations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, alertEscalationPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &alertEscalationR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			AlertEscalations: AlertEscalationSlice{o},
		}
	} else {
		related.R.AlertEscalations = append(related.R.AlertEscalations, o)
	}

	return nil
}

// AlertEscalations retrieves all the records using an executor.
func AlertEscalations(mods ...qm.QueryMod) alertEscalationQuery {
	mods = append(mods, qm.From("\"alert_escalations\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"alert_escalations\".*"})
	}

	return alertEscalationQuery{q}
}

// FindAlertEscalation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAlertEscalation(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AlertEscalation, error) {
	alertEscalationObj := &AlertEscalation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"alert_escalations\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, alertEscalationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from alert_escalations")
	}

	if err = alertEscalationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return alertEscalationObj, err
	}

	return alertEscalationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AlertEscalation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no alert_escalations provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(alertEscalationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	alertEscalationInsertCacheMut.RLock()
	cache, cached := alertEscalationInsertCache[key]
	alertEscalationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			alertEscalationAllColumns,
			alertEscalationColumnsWithDefault,
			alertEscalationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(alertEscalationType, alertEscalationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(alertEscalationType, alertEscalationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"alert_escalations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"alert_escalations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into alert_escalations")
	}

	if !cached {
		alertEscalationInsertCacheMut.Lock()
		alertEscalationInsertCache[key] = cache
		alertEscalationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AlertEscalation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AlertEscalation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	alertEscalationUpdateCacheMut.RLock()
	cache, cached := alertEscalationUpdateCache[key]
	alertEscalationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			alertEscalationAllColumns,
			alertEscalationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update alert_escalations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"alert_escalations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, alertEscalationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(alertEscalationType, alertEscalationMapping, append(wl, alertEscalationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update alert_escalations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for alert_escalations")
	}

	if !cached {
		alertEscalationUpdateCacheMut.Lock()
		alertEscalationUpdateCache[key] = cache
		alertEscalationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q alertEscalationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for alert_escalations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for alert_escalations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AlertEscalationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertEscalationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"alert_escalations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, alertEscalationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in alertEscalation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all alertEscalation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AlertEscalation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no alert_escalations provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(alertEscalationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	alertEscalationUpsertCacheMut.RLock()
	cache, cached := alertEscalationUpsertCache[key]
	alertEscalationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			alertEscalationAllColumns,
			alertEscalationColumnsWithDefault,
			alertEscalationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			alertEscalationAllColumns,
			alertEscalationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert alert_escalations, could not build update column list")
		}

		ret := strmangle.SetComplement(alertEscalationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(alertEscalationPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert alert_escalations, could not build conflict column list")
			}

			conflict = make([]string, len(alertEscalationPrimaryKeyColumns))
			copy(conflict, alertEscalationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"alert_escalations\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(alertEscalationType, alertEscalationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(alertEscalationType, alertEscalationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert alert_escalations")
	}

	if !cached {
		alertEscalationUpsertCacheMut.Lock()
		alertEscalationUpsertCache[key] = cache
		alertEscalationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AlertEscalation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AlertEscalation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no AlertEscalation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), alertEscalationPrimaryKeyMapping)
	sql := "DELETE FROM \"alert_escalations\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from alert_escalations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for alert_escalations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q alertEscalationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no alertEscalationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from alert_escalations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for alert_escalations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AlertEscalationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(alertEscalationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertEscalationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"alert_escalations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, alertEscalationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from alertEscalation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for alert_escalations")
	}

	if len(alertEscalationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AlertEscalation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAlertEscalation(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AlertEscalationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AlertEscalationSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertEscalationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"alert_escalations\".* FROM \"alert_escalations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, alertEscalationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in AlertEscalationSlice")
	}

	*o = slice

	return nil
}

// AlertEscalationExists checks if the AlertEscalation row exists.
func AlertEscalationExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"alert_escalations\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if alert_escalations exists")
	}

	return exists, nil
}

// Exists checks if the AlertEscalation row exists.
func (o *AlertEscalation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AlertEscalationExists(ctx, exec, o.ID)
}
