// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AlertSilence is an object representing the database table.
type AlertSilence struct {
	ID              string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID     string      `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	Kind            string      `boil:"kind" json:"kind" toml:"kind" yaml:"kind"`
	Reason          string      `boil:"reason" json:"reason" toml:"reason" yaml:"reason"`
	CreatedBy       string      `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	CreatedByUserID null.String `boil:"created_by_user_id" json:"created_by_user_id,omitempty" toml:"created_by_user_id" yaml:"created_by_user_id,omitempty"`
	StartsAt        time.Time   `boil:"starts_at" json:"starts_at" toml:"starts_at" yaml:"starts_at"`
	EndsAt          time.Time   `boil:"ends_at" json:"ends_at" toml:"ends_at" yaml:"ends_at"`
	CreatedAt       time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *alertSilenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L alertSilenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AlertSilenceColumns = struct {
	ID              string
	WorkspaceID     string
	Kind            string
	Reason          string
	CreatedBy       string
	CreatedByUserID string
	StartsAt        string
	EndsAt          string
	CreatedAt       string
}{
	ID:              "id",
	WorkspaceID:     "workspace_id",
	Kind:            "kind",
	Reason:          "reason",
	CreatedBy:       "created_by",
	CreatedByUserID: "created_by_user_id",
	StartsAt:        "starts_at",
	EndsAt:          "ends_at",
	CreatedAt:       "created_at",
}

var AlertSilenceTableColumns = struct {
	ID              string
	WorkspaceID     string
	Kind            string
	Reason          string
	CreatedBy       string
	CreatedByUserID string
	StartsAt        string
	EndsAt          string
	CreatedAt       string
}{
	ID:              "alert_silences.id",
	WorkspaceID:     "alert_silences.workspace_id",
	Kind:            "alert_silences.kind",
	Reason:          "alert_silences.reason",
	CreatedBy:       "alert_silences.created_by",
	CreatedByUserID: "alert_silences.created_by_user_id",
	StartsAt:        "alert_silences.starts_at",
	EndsAt:          "alert_silences.ends_at",
	CreatedAt:       "alert_silences.created_at",
}

// Generated where

var AlertSilenceWhere = struct {
	ID              whereHelperstring
	WorkspaceID     whereHelperstring
	Kind            whereHelperstring
	Reason          whereHelperstring
	CreatedBy       whereHelperstring
	CreatedByUserID whereHelpernull_String
	StartsAt        whereHelpertime_Time
	EndsAt          whereHelpertime_Time
	CreatedAt       whereHelpertime_Time
}{
	ID:              whereHelperstring{field: "\"alert_silences\".\"id\""},
	WorkspaceID:     whereHelperstring{field: "\"alert_silences\".\"workspace_id\""},
	Kind:            whereHelperstring{field: "\"alert_silences\".\"kind\""},
	Reason:          whereHelperstring{field: "\"alert_silences\".\"reason\""},
	CreatedBy:       whereHelperstring{field: "\"alert_silences\".\"created_by\""},
	CreatedByUserID: whereHelpernull_String{field: "\"alert_silences\".\"created_by_user_id\""},
	StartsAt:        whereHelpertime_Time{field: "\"alert_silences\".\"starts_at\""},
	EndsAt:          whereHelpertime_Time{field: "\"alert_silences\".\"ends_at\""},
	CreatedAt:       whereHelpertime_Time{field: "\"alert_silences\".\"created_at\""},
}

// AlertSilenceRels is where relationship names are stored.
var AlertSilenceRels = struct {
	CreatedByUser                 string
	Workspace                     string
	SilenceAlertSilenceConditions string
	SuppressedBySilenceAlerts     string
}{
	CreatedByUser:                 "CreatedByUser",
	Workspace:                     "Workspace",
	SilenceAlertSilenceConditions: "SilenceAlertSilenceConditions",
	SuppressedBySilenceAlerts:     "SuppressedBySilenceAlerts",
}

// alertSilenceR is where relationships are stored.
type alertSilenceR struct {
	CreatedByUser                 *User                      `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	Workspace                     *Workspace                 `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
	SilenceAlertSilenceConditions AlertSilenceConditionSlice `boil:"SilenceAlertSilenceConditions" json:"SilenceAlertSilenceConditions" toml:"SilenceAlertSilenceConditions" yaml:"SilenceAlertSilenceConditions"`
	SuppressedBySilenceAlerts     AlertSlice                 `boil:"SuppressedBySilenceAlerts" json:"SuppressedBySilenceAlerts" toml:"SuppressedBySilenceAlerts" yaml:"SuppressedBySilenceAlerts"`
}

// NewStruct creates a new relationship struct
func (*alertSilenceR) NewStruct() *alertSilenceR {
	return &alertSilenceR{}
}

func (o *AlertSilence) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *alertSilenceR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *AlertSilence) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *alertSilenceR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

func (o *AlertSilence) GetSilenceAlertSilenceConditions() AlertSilenceConditionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSilenceAlertSilenceConditions()
}

func (r *alertSilenceR) GetSilenceAlertSilenceConditions() AlertSilenceConditionSlice {
	if r == nil {
		return nil
	}

	return r.SilenceAlertSilenceConditions
}

func (o *AlertSilence) GetSuppressedBySilenceAlerts() AlertSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSuppressedBySilenceAlerts()
}

func (r *alertSilenceR) GetSuppressedBySilenceAlerts() AlertSlice {
	if r == nil {
		return nil
	}

	return r.SuppressedBySilenceAlerts
}

// alertSilenceL is where Load methods for each relationship are stored.
type alertSilenceL struct{}

var (
	alertSilenceAllColumns            = []string{"id", "workspace_id", "kind", "reason", "created_by", "created_by_user_id", "starts_at", "ends_at", "created_at"}
	alertSilenceColumnsWithoutDefault = []string{"workspace_id", "starts_at", "ends_at"}
	alertSilenceColumnsWithDefault    = []string{"id", "kind", "reason", "created_by", "created_by_user_id", "created_at"}
	alertSilencePrimaryKeyColumns     = []string{"id"}
	alertSilenceGeneratedColumns      = []string{}
)

type (
	// AlertSilenceSlice is an alias for a slice of pointers to AlertSilence.
	// This should almost always be used instead of []AlertSilence.
	AlertSilenceSlice []*AlertSilence
	// AlertSilenceHook is the signature for custom AlertSilence hook methods
	AlertSilenceHook func(context.Context, boil.ContextExecutor, *AlertSilence) error

	alertSilenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	alertSilenceType                 = reflect.TypeOf(&AlertSilence{})
	alertSilenceMapping              = queries.MakeStructMapping(alertSilenceType)
	alertSilencePrimaryKeyMapping, _ = queries.BindMapping(alertSilenceType, alertSilenceMapping, alertSilencePrimaryKeyColumns)
	alertSilenceInsertCacheMut       sync.RWMutex
	alertSilenceInsertCache          = make(map[string]insertCache)
	alertSilenceUpdateCacheMut       sync.RWMutex
	alertSilenceUpdateCache          = make(map[string]updateCache)
	alertSilenceUpsertCacheMut       sync.RWMutex
	alertSilenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var alertSilenceAfterSelectMu sync.Mutex
var alertSilenceAfterSelectHooks []AlertSilenceHook

var alertSilenceBeforeInsertMu sync.Mutex
var alertSilenceBeforeInsertHooks []AlertSilenceHook
var alertSilenceAfterInsertMu sync.Mutex
var alertSilenceAfterInsertHooks []AlertSilenceHook

var alertSilenceBeforeUpdateMu sync.Mutex
var alertSilenceBeforeUpdateHooks []AlertSilenceHook
var alertSilenceAfterUpdateMu sync.Mutex
var alertSilenceAfterUpdateHooks []AlertSilenceHook

var alertSilenceBeforeDeleteMu sync.Mutex
var alertSilenceBeforeDeleteHooks []AlertSilenceHook
var alertSilenceAfterDeleteMu sync.Mutex
var alertSilenceAfterDeleteHooks []AlertSilenceHook

var alertSilenceBeforeUpsertMu sync.Mutex
var alertSilenceBeforeUpsertHooks []AlertSilenceHook
var alertSilenceAfterUpsertMu sync.Mutex
var alertSilenceAfterUpsertHooks []AlertSilenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AlertSilence) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AlertSilence) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AlertSilence) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AlertSilence) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AlertSilence) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AlertSilence) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AlertSilence) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AlertSilence) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AlertSilence) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertSilenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAlertSilenceHook registers your hook function for all future operations.
func AddAlertSilenceHook(hookPoint boil.HookPoint, alertSilenceHook AlertSilenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		alertSilenceAfterSelectMu.Lock()
		alertSilenceAfterSelectHooks = append(alertSilenceAfterSelectHooks, alertSilenceHook)
		alertSilenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		alertSilenceBeforeInsertMu.Lock()
		alertSilenceBeforeInsertHooks = append(alertSilenceBeforeInsertHooks, alertSilenceHook)
		alertSilenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		alertSilenceAfterInsertMu.Lock()
		alertSilenceAfterInsertHooks = append(alertSilenceAfterInsertHooks, alertSilenceHook)
		alertSilenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		alertSilenceBeforeUpdateMu.Lock()
		alertSilenceBeforeUpdateHooks = append(alertSilenceBeforeUpdateHooks, alertSilenceHook)
		alertSilenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		alertSilenceAfterUpdateMu.Lock()
		alertSilenceAfterUpdateHooks = append(alertSilenceAfterUpdateHooks, alertSilenceHook)
		alertSilenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		alertSilenceBeforeDeleteMu.Lock()
		alertSilenceBeforeDeleteHooks = append(alertSilenceBeforeDeleteHooks, alertSilenceHook)
		alertSilenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		alertSilenceAfterDeleteMu.Lock()
		alertSilenceAfterDeleteHooks = append(alertSilenceAfterDeleteHooks, alertSilenceHook)
		alertSilenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		alertSilenceBeforeUpsertMu.Lock()
		alertSilenceBeforeUpsertHooks = append(alertSilenceBeforeUpsertHooks, alertSilenceHook)
		alertSilenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		alertSilenceAfterUpsertMu.Lock()
		alertSilenceAfterUpsertHooks = append(alertSilenceAfterUpsertHooks, alertSilenceHook)
		alertSilenceAfterUpsertMu.Unlock()
	}
}

// One returns a single alertSilence record from the query.
func (q alertSilenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AlertSilence, error) {
	o := &AlertSilence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for alert_silences")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AlertSilence records from the query.
func (q alertSilenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (AlertSilenceSlice, error) {
	var o []*AlertSilence

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to AlertSilence slice")
	}

	if len(alertSilenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AlertSilence records in the query.
func (q alertSilenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count alert_silences rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q alertSilenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if alert_silences exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *AlertSilence) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedByUserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Workspace pointed to by the foreign key.
func (o *AlertSilence) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// SilenceAlertSilenceConditions retrieves all the alert_silence_condition's AlertSilenceConditions with an executor via silence_id column.
func (o *AlertSilence) SilenceAlertSilenceConditions(mods ...qm.QueryMod) alertSilenceConditionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"alert_silence_conditions\".\"silence_id\"=?", o.ID),
	)

	return AlertSilenceConditions(queryMods...)
}

// SuppressedBySilenceAlerts retrieves all the alert's Alerts with an executor via suppressed_by_silence_id column.
func (o *AlertSilence) SuppressedBySilenceAlerts(mods ...qm.QueryMod) alertQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"alerts\".\"suppressed_by_silence_id\"=?", o.ID),
	)

	return Alerts(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (alertSilenceL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertSilence any, mods queries.Applicator) error {
	var slice []*AlertSilence
	var object *AlertSilence

	if singular {
		var ok bool
		object, ok = maybeAlertSilence.(*AlertSilence)
		if !ok {
			object = new(AlertSilence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertSilence))
			}
		}
	} else {
		s, ok := maybeAlertSilence.(*[]*AlertSilence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertSilence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertSilenceR{}
		}
		if !queries.IsNil(object.CreatedByUserID) {
			args[object.CreatedByUserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertSilenceR{}
			}

			if !queries.IsNil(obj.CreatedByUserID) {
				args[obj.CreatedByUserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByUserAlertSilences = append(foreign.R.CreatedByUserAlertSilences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.CreatedByUserID, foreign.ID) {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByUserAlertSilences = append(foreign.R.CreatedByUserAlertSilences, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (alertSilenceL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertSilence any, mods queries.Applicator) error {
	var slice []*AlertSilence
	var object *AlertSilence

	if singular {
		var ok bool
		object, ok = maybeAlertSilence.(*AlertSilence)
		if !ok {
			object = new(AlertSilence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertSilence))
			}
		}
	} else {
		s, ok := maybeAlertSilence.(*[]*AlertSilence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertSilence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertSilenceR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertSilenceR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.AlertSilences = append(foreign.R.AlertSilences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.AlertSilences = append(foreign.R.AlertSilences, local)
				break
			}
		}
	}

	return nil
}

// LoadSilenceAlertSilenceConditions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (alertSilenceL) LoadSilenceAlertSilenceConditions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertSilence any, mods queries.Applicator) error {
	var slice []*AlertSilence
	var object *AlertSilence

	if singular {
		var ok bool
		object, ok = maybeAlertSilence.(*AlertSilence)
		if !ok {
			object = new(AlertSilence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertSilence))
			}
		}
	} else {
		s, ok := maybeAlertSilence.(*[]*AlertSilence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertSilence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertSilenceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertSilenceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`alert_silence_conditions`),
		qm.WhereIn(`alert_silence_conditions.silence_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load alert_silence_conditions")
	}

	var resultSlice []*AlertSilenceCondition
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice alert_silence_conditions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on alert_silence_conditions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for alert_silence_conditions")
	}

	if len(alertSilenceConditionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SilenceAlertSilenceConditions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &alertSilenceConditionR{}
			}
			foreign.R.Silence = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SilenceID {
				local.R.SilenceAlertSilenceConditions = append(local.R.SilenceAlertSilenceConditions, foreign)
				if foreign.R == nil {
					foreign.R = &alertSilenceConditionR{}
				}
				foreign.R.Silence = local
				break
			}
		}
	}

	return nil
}

// LoadSuppressedBySilenceAlerts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (alertSilenceL) LoadSuppressedBySilenceAlerts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertSilence any, mods queries.Applicator) error {
	var slice []*AlertSilence
	var object *AlertSilence

	if singular {
		var ok bool
		object, ok = maybeAlertSilence.(*AlertSilence)
		if !ok {
			object = new(AlertSilence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertSilence))
			}
		}
	} else {
		s, ok := maybeAlertSilence.(*[]*AlertSilence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertSilence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertSilence))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertSilenceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertSilenceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`alerts`),
		qm.WhereIn(`alerts.suppressed_by_silence_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load alerts")
	}

	var resultSlice []*Alert
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice alerts")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on alerts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for alerts")
	}

	if len(alertAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.SuppressedBySilenceAlerts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &alertR{}
			}
			foreign.R.SuppressedBySilence = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.SuppressedBySilenceID) {
				local.R.SuppressedBySilenceAlerts = append(local.R.SuppressedBySilenceAlerts, foreign)
				if foreign.R == nil {
					foreign.R = &alertR{}
				}
				foreign.R.SuppressedBySilence = local
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the alertSilence to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByUserAlertSilences.
func (o *AlertSilence) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alert_silences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by_user_id"}),
		strmangle.WhereClause("\"", "\"", 2, alertSilencePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.CreatedByUserID, related.ID)
	if o.R == nil {
		o.R = &alertSilenceR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByUserAlertSilences: AlertSilenceSlice{o},
		}
	} else {
		related.R.CreatedByUserAlertSilences = append(related.R.CreatedByUserAlertSilences, o)
	}

	return nil
}

// RemoveCreatedByUser relationship.
// Sets o.R.CreatedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *AlertSilence) RemoveCreatedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.CreatedByUserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("created_by_user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.CreatedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.CreatedByUserAlertSilences {
		if queries.Equal(o.CreatedByUserID, ri.CreatedByUserID) {
			continue
		}

		ln := len(related.R.CreatedByUserAlertSilences)
		if ln > 1 && i < ln-1 {
			related.R.CreatedByUserAlertSilences[i] = related.R.CreatedByUserAlertSilences[ln-1]
		}
		related.R.CreatedByUserAlertSilences = related.R.CreatedByUserAlertSilences[:ln-1]
		break
	}
	return nil
}

// SetWorkspace of the alertSilence to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.AlertSilences.
func (o *AlertSilence) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alert_silences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, alertSilencePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &alertSilenceR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			AlertSilences: AlertSilenceSlice{o},
		}
	} else {
		related.R.AlertSilences = append(related.R.AlertSilences, o)
	}

	return nil
}

// AddSilenceAlertSilenceConditions adds the given related objects to the existing relationships
// of the alert_silence, optionally inserting them as new records.
// Appends related to o.R.SilenceAlertSilenceConditions.
// Sets related.R.Silence appropriately.
func (o *AlertSilence) AddSilenceAlertSilenceConditions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*AlertSilenceCondition) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SilenceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"alert_silence_conditions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"silence_id"}),
				strmangle.WhereClause("\"", "\"", 2, alertSilenceConditionPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SilenceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &alertSilenceR{
			SilenceAlertSilenceConditions: related,
		}
	} else {
		o.R.SilenceAlertSilenceConditions = append(o.R.SilenceAlertSilenceConditions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &alertSilenceConditionR{
				Silence: o,
			}
		} else {
			rel.R.Silence = o
		}
	}
	return nil
}

// AddSuppressedBySilenceAlerts adds the given related objects to the existing relationships
// of the alert_silence, optionally inserting them as new records.
// Appends related to o.R.SuppressedBySilenceAlerts.
// Sets related.R.SuppressedBySilence appropriately.
func (o *AlertSilence) AddSuppressedBySilenceAlerts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Alert) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.SuppressedBySilenceID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"alerts\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"suppressed_by_silence_id"}),
				strmangle.WhereClause("\"", "\"", 2, alertPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.SuppressedBySilenceID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &alertSilenceR{
			SuppressedBySilenceAlerts: related,
		}
	} else {
		o.R.SuppressedBySilenceAlerts = append(o.R.SuppressedBySilenceAlerts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &alertR{
				SuppressedBySilence: o,
			}
		} else {
			rel.R.SuppressedBySilence = o
		}
	}
	return nil
}

// SetSuppressedBySilenceAlerts removes all previously related items of the
// alert_silence replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.SuppressedBySilence's SuppressedBySilenceAlerts accordingly.
// Replaces o.R.SuppressedBySilenceAlerts with related.
// Sets related.R.SuppressedBySilence's SuppressedBySilenceAlerts accordingly.
func (o *AlertSilence) SetSuppressedBySilenceAlerts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Alert) error {
	query := "update \"alerts\" set \"suppressed_by_silence_id\" = null where \"suppressed_by_silence_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SuppressedBySilenceAlerts {
			queries.SetScanner(&rel.SuppressedBySilenceID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.SuppressedBySilence = nil
		}
		o.R.SuppressedBySilenceAlerts = nil
	}

	return o.AddSuppressedBySilenceAlerts(ctx, exec, insert, related...)
}

// RemoveSuppressedBySilenceAlerts relationships from objects passed in.
// Removes related items from R.SuppressedBySilenceAlerts (uses pointer comparison, removal does not keep order)
// Sets related.R.SuppressedBySilence.
func (o *AlertSilence) RemoveSuppressedBySilenceAlerts(ctx context.Context, exec boil.ContextExecutor, related ...*Alert) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.SuppressedBySilenceID, nil)
		if rel.R != nil {
			rel.R.SuppressedBySilence = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("suppressed_by_silence_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SuppressedBySilenceAlerts {
			if rel != ri {
				continue
			}

			ln := len(o.R.SuppressedBySilenceAlerts)
			if ln > 1 && i < ln-1 {
				o.R.SuppressedBySilenceAlerts[i] = o.R.SuppressedBySilenceAlerts[ln-1]
			}
			o.R.SuppressedBySilenceAlerts = o.R.SuppressedBySilenceAlerts[:ln-1]
			break
		}
	}

	return nil
}

// AlertSilences retrieves all the records using an executor.
func AlertSilences(mods ...qm.QueryMod) alertSilenceQuery {
	mods = append(mods, qm.From("\"alert_silences\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"alert_silences\".*"})
	}

	return alertSilenceQuery{q}
}

// FindAlertSilence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAlertSilence(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AlertSilence, error) {
	alertSilenceObj := &AlertSilence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"alert_silences\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, alertSilenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from alert_silences")
	}

	if err = alertSilenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return alertSilenceObj, err
	}

	return alertSilenceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AlertSilence) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no alert_silences provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(alertSilenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	alertSilenceInsertCacheMut.RLock()
	cache, cached := alertSilenceInsertCache[key]
	alertSilenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			alertSilenceAllColumns,
			alertSilenceColumnsWithDefault,
			alertSilenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(alertSilenceType, alertSilenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(alertSilenceType, alertSilenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"alert_silences\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"alert_silences\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into alert_silences")
	}

	if !cached {
		alertSilenceInsertCacheMut.Lock()
		alertSilenceInsertCache[key] = cache
		alertSilenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AlertSilence.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AlertSilence) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	alertSilenceUpdateCacheMut.RLock()
	cache, cached := alertSilenceUpdateCache[key]
	alertSilenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			alertSilenceAllColumns,
			alertSilencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update alert_silences, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"alert_silences\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, alertSilencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(alertSilenceType, alertSilenceMapping, append(wl, alertSilencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update alert_silences row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for alert_silences")
	}

	if !cached {
		alertSilenceUpdateCacheMut.Lock()
		alertSilenceUpdateCache[key] = cache
		alertSilenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q alertSilenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for alert_silences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for alert_silences")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AlertSilenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertSilencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"alert_silences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, alertSilencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in alertSilence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all alertSilence")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AlertSilence) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no alert_silences provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(alertSilenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	alertSilenceUpsertCacheMut.RLock()
	cache, cached := alertSilenceUpsertCache[key]
	alertSilenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			alertSilenceAllColumns,
			alertSilenceColumnsWithDefault,
			alertSilenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			alertSilenceAllColumns,
			alertSilencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert alert_silences, could not build update column list")
		}

		ret := strmangle.SetComplement(alertSilenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(alertSilencePrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert alert_silences, could not build conflict column list")
			}

			conflict = make([]string, len(alertSilencePrimaryKeyColumns))
			copy(conflict, alertSilencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"alert_silences\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(alertSilenceType, alertSilenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(alertSilenceType, alertSilenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert alert_silences")
	}

	if !cached {
		alertSilenceUpsertCacheMut.Lock()
		alertSilenceUpsertCache[key] = cache
		alertSilenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AlertSilence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AlertSilence) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no AlertSilence provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), alertSilencePrimaryKeyMapping)
	sql := "DELETE FROM \"alert_silences\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from alert_silences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for alert_silences")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q alertSilenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no alertSilenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from alert_silences")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for alert_silences")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AlertSilenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(alertSilenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertSilencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"alert_silences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, alertSilencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from alertSilence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for alert_silences")
	}

	if len(alertSilenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AlertSilence) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAlertSilence(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AlertSilenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AlertSilenceSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertSilencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"alert_silences\".* FROM \"alert_silences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, alertSilencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in AlertSilenceSlice")
	}

	*o = slice

	return nil
}

// AlertSilenceExists checks if the AlertSilence row exists.
func AlertSilenceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"alert_silences\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if alert_silences exists")
	}

	return exists, nil
}

// Exists checks if the AlertSilence row exists.
func (o *AlertSilence) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AlertSilenceExists(ctx, exec, o.ID)
}
