// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// AlertGroupRule is an object representing the database table.
type AlertGroupRule struct {
	ID            string            `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID   string            `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	Fields        types.StringArray `boil:"fields" json:"fields" toml:"fields" yaml:"fields"`
	WindowSeconds int               `boil:"window_seconds" json:"window_seconds" toml:"window_seconds" yaml:"window_seconds"`
	Position      int               `boil:"position" json:"position" toml:"position" yaml:"position"`
	CreatedAt     time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *alertGroupRuleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L alertGroupRuleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AlertGroupRuleColumns = struct {
	ID            string
	WorkspaceID   string
	Fields        string
	WindowSeconds string
	Position      string
	CreatedAt     string
}{
	ID:            "id",
	WorkspaceID:   "workspace_id",
	Fields:        "fields",
	WindowSeconds: "window_seconds",
	Position:      "position",
	CreatedAt:     "created_at",
}

var AlertGroupRuleTableColumns = struct {
	ID            string
	WorkspaceID   string
	Fields        string
	WindowSeconds string
	Position      string
	CreatedAt     string
}{
	ID:            "alert_group_rules.id",
	WorkspaceID:   "alert_group_rules.workspace_id",
	Fields:        "alert_group_rules.fields",
	WindowSeconds: "alert_group_rules.window_seconds",
	Position:      "alert_group_rules.position",
	CreatedAt:     "alert_group_rules.created_at",
}

// Generated where

type whereHelpertypes_StringArray struct{ field string }

func (w whereHelpertypes_StringArray) EQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_StringArray) NEQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_StringArray) LT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_StringArray) LTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_StringArray) GT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_StringArray) GTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var AlertGroupRuleWhere = struct {
	ID            whereHelperstring
	WorkspaceID   whereHelperstring
	Fields        whereHelpertypes_StringArray
	WindowSeconds whereHelperint
	Position      whereHelperint
	CreatedAt     whereHelpertime_Time
}{
	ID:            whereHelperstring{field: "\"alert_group_rules\".\"id\""},
	WorkspaceID:   whereHelperstring{field: "\"alert_group_rules\".\"workspace_id\""},
	Fields:        whereHelpertypes_StringArray{field: "\"alert_group_rules\".\"fields\""},
	WindowSeconds: whereHelperint{field: "\"alert_group_rules\".\"window_seconds\""},
	Position:      whereHelperint{field: "\"alert_group_rules\".\"position\""},
	CreatedAt:     whereHelpertime_Time{field: "\"alert_group_rules\".\"created_at\""},
}

// AlertGroupRuleRels is where relationship names are stored.
var AlertGroupRuleRels = struct {
	Workspace string
}{
	Workspace: "Workspace",
}

// alertGroupRuleR is where relationships are stored.
type alertGroupRuleR struct {
	Workspace *Workspace `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
}

// NewStruct creates a new relationship struct
func (*alertGroupRuleR) NewStruct() *alertGroupRuleR {
	return &alertGroupRuleR{}
}

func (o *AlertGroupRule) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *alertGroupRuleR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

// alertGroupRuleL is where Load methods for each relationship are stored.
type alertGroupRuleL struct{}

var (
	alertGroupRuleAllColumns            = []string{"id", "workspace_id", "fields", "window_seconds", "position", "created_at"}
	alertGroupRuleColumnsWithoutDefault = []string{"workspace_id", "fields"}
	alertGroupRuleColumnsWithDefault    = []string{"id", "window_seconds", "position", "created_at"}
	alertGroupRulePrimaryKeyColumns     = []string{"id"}
	alertGroupRuleGeneratedColumns      = []string{}
)

type (
	// AlertGroupRuleSlice is an alias for a slice of pointers to AlertGroupRule.
	// This should almost always be used instead of []AlertGroupRule.
	AlertGroupRuleSlice []*AlertGroupRule
	// AlertGroupRuleHook is the signature for custom AlertGroupRule hook methods
	AlertGroupRuleHook func(context.Context, boil.ContextExecutor, *AlertGroupRule) error

	alertGroupRuleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	alertGroupRuleType                 = reflect.TypeOf(&AlertGroupRule{})
	alertGroupRuleMapping              = queries.MakeStructMapping(alertGroupRuleType)
	alertGroupRulePrimaryKeyMapping, _ = queries.BindMapping(alertGroupRuleType, alertGroupRuleMapping, alertGroupRulePrimaryKeyColumns)
	alertGroupRuleInsertCacheMut       sync.RWMutex
	alertGroupRuleInsertCache          = make(map[string]insertCache)
	alertGroupRuleUpdateCacheMut       sync.RWMutex
	alertGroupRuleUpdateCache          = make(map[string]updateCache)
	alertGroupRuleUpsertCacheMut       sync.RWMutex
	alertGroupRuleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var alertGroupRuleAfterSelectMu sync.Mutex
var alertGroupRuleAfterSelectHooks []AlertGroupRuleHook

var alertGroupRuleBeforeInsertMu sync.Mutex
var alertGroupRuleBeforeInsertHooks []AlertGroupRuleHook
var alertGroupRuleAfterInsertMu sync.Mutex
var alertGroupRuleAfterInsertHooks []AlertGroupRuleHook

var alertGroupRuleBeforeUpdateMu sync.Mutex
var alertGroupRuleBeforeUpdateHooks []AlertGroupRuleHook
var alertGroupRuleAfterUpdateMu sync.Mutex
var alertGroupRuleAfterUpdateHooks []AlertGroupRuleHook

var alertGroupRuleBeforeDeleteMu sync.Mutex
var alertGroupRuleBeforeDeleteHooks []AlertGroupRuleHook
var alertGroupRuleAfterDeleteMu sync.Mutex
var alertGroupRuleAfterDeleteHooks []AlertGroupRuleHook

var alertGroupRuleBeforeUpsertMu sync.Mutex
var alertGroupRuleBeforeUpsertHooks []AlertGroupRuleHook
var alertGroupRuleAfterUpsertMu sync.Mutex
var alertGroupRuleAfterUpsertHooks []AlertGroupRuleHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AlertGroupRule) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AlertGroupRule) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AlertGroupRule) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AlertGroupRule) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AlertGroupRule) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AlertGroupRule) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AlertGroupRule) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AlertGroupRule) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AlertGroupRule) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range alertGroupRuleAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAlertGroupRuleHook registers your hook function for all future operations.
func AddAlertGroupRuleHook(hookPoint boil.HookPoint, alertGroupRuleHook AlertGroupRuleHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		alertGroupRuleAfterSelectMu.Lock()
		alertGroupRuleAfterSelectHooks = append(alertGroupRuleAfterSelectHooks, alertGroupRuleHook)
		alertGroupRuleAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		alertGroupRuleBeforeInsertMu.Lock()
		alertGroupRuleBeforeInsertHooks = append(alertGroupRuleBeforeInsertHooks, alertGroupRuleHook)
		alertGroupRuleBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		alertGroupRuleAfterInsertMu.Lock()
		alertGroupRuleAfterInsertHooks = append(alertGroupRuleAfterInsertHooks, alertGroupRuleHook)
		alertGroupRuleAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		alertGroupRuleBeforeUpdateMu.Lock()
		alertGroupRuleBeforeUpdateHooks = append(alertGroupRuleBeforeUpdateHooks, alertGroupRuleHook)
		alertGroupRuleBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		alertGroupRuleAfterUpdateMu.Lock()
		alertGroupRuleAfterUpdateHooks = append(alertGroupRuleAfterUpdateHooks, alertGroupRuleHook)
		alertGroupRuleAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		alertGroupRuleBeforeDeleteMu.Lock()
		alertGroupRuleBeforeDeleteHooks = append(alertGroupRuleBeforeDeleteHooks, alertGroupRuleHook)
		alertGroupRuleBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		alertGroupRuleAfterDeleteMu.Lock()
		alertGroupRuleAfterDeleteHooks = append(alertGroupRuleAfterDeleteHooks, alertGroupRuleHook)
		alertGroupRuleAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		alertGroupRuleBeforeUpsertMu.Lock()
		alertGroupRuleBeforeUpsertHooks = append(alertGroupRuleBeforeUpsertHooks, alertGroupRuleHook)
		alertGroupRuleBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		alertGroupRuleAfterUpsertMu.Lock()
		alertGroupRuleAfterUpsertHooks = append(alertGroupRuleAfterUpsertHooks, alertGroupRuleHook)
		alertGroupRuleAfterUpsertMu.Unlock()
	}
}

// One returns a single alertGroupRule record from the query.
func (q alertGroupRuleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AlertGroupRule, error) {
	o := &AlertGroupRule{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for alert_group_rules")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all AlertGroupRule records from the query.
func (q alertGroupRuleQuery) All(ctx context.Context, exec boil.ContextExecutor) (AlertGroupRuleSlice, error) {
	var o []*AlertGroupRule

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to AlertGroupRule slice")
	}

	if len(alertGroupRuleAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all AlertGroupRule records in the query.
func (q alertGroupRuleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count alert_group_rules rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q alertGroupRuleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if alert_group_rules exists")
	}

	return count > 0, nil
}

// Workspace pointed to by the foreign key.
func (o *AlertGroupRule) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (alertGroupRuleL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAlertGroupRule any, mods queries.Applicator) error {
	var slice []*AlertGroupRule
	var object *AlertGroupRule

	if singular {
		var ok bool
		object, ok = maybeAlertGroupRule.(*AlertGroupRule)
		if !ok {
			object = new(AlertGroupRule)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAlertGroupRule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAlertGroupRule))
			}
		}
	} else {
		s, ok := maybeAlertGroupRule.(*[]*AlertGroupRule)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAlertGroupRule)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAlertGroupRule))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &alertGroupRuleR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &alertGroupRuleR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.AlertGroupRules = append(foreign.R.AlertGroupRules, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.AlertGroupRules = append(foreign.R.AlertGroupRules, local)
				break
			}
		}
	}

	return nil
}

// SetWorkspace of the alertGroupRule to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.AlertGroupRules.
func (o *AlertGroupRule) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"alert_group_rules\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, alertGroupRulePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &alertGroupRuleR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			AlertGroupRules: AlertGroupRuleSlice{o},
		}
	} else {
		related.R.AlertGroupRules = append(related.R.AlertGroupRules, o)
	}

	return nil
}

// AlertGroupRules retrieves all the records using an executor.
func AlertGroupRules(mods ...qm.QueryMod) alertGroupRuleQuery {
	mods = append(mods, qm.From("\"alert_group_rules\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"alert_group_rules\".*"})
	}

	return alertGroupRuleQuery{q}
}

// FindAlertGroupRule retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAlertGroupRule(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*AlertGroupRule, error) {
	alertGroupRuleObj := &AlertGroupRule{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"alert_group_rules\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, alertGroupRuleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from alert_group_rules")
	}

	if err = alertGroupRuleObj.doAfterSelectHooks(ctx, exec); err != nil {
		return alertGroupRuleObj, err
	}

	return alertGroupRuleObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AlertGroupRule) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no alert_group_rules provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(alertGroupRuleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	alertGroupRuleInsertCacheMut.RLock()
	cache, cached := alertGroupRuleInsertCache[key]
	alertGroupRuleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			alertGroupRuleAllColumns,
			alertGroupRuleColumnsWithDefault,
			alertGroupRuleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(alertGroupRuleType, alertGroupRuleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(alertGroupRuleType, alertGroupRuleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"alert_group_rules\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"alert_group_rules\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into alert_group_rules")
	}

	if !cached {
		alertGroupRuleInsertCacheMut.Lock()
		alertGroupRuleInsertCache[key] = cache
		alertGroupRuleInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the AlertGroupRule.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AlertGroupRule) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	alertGroupRuleUpdateCacheMut.RLock()
	cache, cached := alertGroupRuleUpdateCache[key]
	alertGroupRuleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			alertGroupRuleAllColumns,
			alertGroupRulePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update alert_group_rules, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"alert_group_rules\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, alertGroupRulePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(alertGroupRuleType, alertGroupRuleMapping, append(wl, alertGroupRulePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update alert_group_rules row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for alert_group_rules")
	}

	if !cached {
		alertGroupRuleUpdateCacheMut.Lock()
		alertGroupRuleUpdateCache[key] = cache
		alertGroupRuleUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q alertGroupRuleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for alert_group_rules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for alert_group_rules")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AlertGroupRuleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertGroupRulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"alert_group_rules\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, alertGroupRulePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in alertGroupRule slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all alertGroupRule")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AlertGroupRule) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no alert_group_rules provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(alertGroupRuleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	alertGroupRuleUpsertCacheMut.RLock()
	cache, cached := alertGroupRuleUpsertCache[key]
	alertGroupRuleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			alertGroupRuleAllColumns,
			alertGroupRuleColumnsWithDefault,
			alertGroupRuleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			alertGroupRuleAllColumns,
			alertGroupRulePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert alert_group_rules, could not build update column list")
		}

		ret := strmangle.SetComplement(alertGroupRuleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(alertGroupRulePrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert alert_group_rules, could not build conflict column list")
			}

			conflict = make([]string, len(alertGroupRulePrimaryKeyColumns))
			copy(conflict, alertGroupRulePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"alert_group_rules\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(alertGroupRuleType, alertGroupRuleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(alertGroupRuleType, alertGroupRuleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert alert_group_rules")
	}

	if !cached {
		alertGroupRuleUpsertCacheMut.Lock()
		alertGroupRuleUpsertCache[key] = cache
		alertGroupRuleUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single AlertGroupRule record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AlertGroupRule) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no AlertGroupRule provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), alertGroupRulePrimaryKeyMapping)
	sql := "DELETE FROM \"alert_group_rules\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from alert_group_rules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for alert_group_rules")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q alertGroupRuleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no alertGroupRuleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from alert_group_rules")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for alert_group_rules")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AlertGroupRuleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(alertGroupRuleBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertGroupRulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"alert_group_rules\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, alertGroupRulePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from alertGroupRule slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for alert_group_rules")
	}

	if len(alertGroupRuleAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AlertGroupRule) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAlertGroupRule(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AlertGroupRuleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AlertGroupRuleSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), alertGroupRulePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"alert_group_rules\".* FROM \"alert_group_rules\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, alertGroupRulePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in AlertGroupRuleSlice")
	}

	*o = slice

	return nil
}

// AlertGroupRuleExists checks if the AlertGroupRule row exists.
func AlertGroupRuleExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"alert_group_rules\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if alert_group_rules exists")
	}

	return exists, nil
}

// Exists checks if the AlertGroupRule row exists.
func (o *AlertGroupRule) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AlertGroupRuleExists(ctx, exec, o.ID)
}
