// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ChatConnection is an object representing the database table.
type ChatConnection struct {
	ID               string            `boil:"id" json:"id" toml:"id" yaml:"id"`
	WorkspaceID      string            `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	Provider         string            `boil:"provider" json:"provider" toml:"provider" yaml:"provider"`
	ExternalID       string            `boil:"external_id" json:"external_id" toml:"external_id" yaml:"external_id"`
	ExternalName     string            `boil:"external_name" json:"external_name" toml:"external_name" yaml:"external_name"`
	BotUserID        string            `boil:"bot_user_id" json:"bot_user_id" toml:"bot_user_id" yaml:"bot_user_id"`
	BotTokenEnc      null.Bytes        `boil:"bot_token_enc" json:"bot_token_enc,omitempty" toml:"bot_token_enc" yaml:"bot_token_enc,omitempty"`
	AppID            string            `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id"`
	TenantID         string            `boil:"tenant_id" json:"tenant_id" toml:"tenant_id" yaml:"tenant_id"`
	ServiceURL       string            `boil:"service_url" json:"service_url" toml:"service_url" yaml:"service_url"`
	HookTokenHash    null.String       `boil:"hook_token_hash" json:"hook_token_hash,omitempty" toml:"hook_token_hash" yaml:"hook_token_hash,omitempty"`
	HookSecretEnc    null.Bytes        `boil:"hook_secret_enc" json:"hook_secret_enc,omitempty" toml:"hook_secret_enc" yaml:"hook_secret_enc,omitempty"`
	Scopes           types.StringArray `boil:"scopes" json:"scopes" toml:"scopes" yaml:"scopes"`
	Enabled          bool              `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`
	Health           string            `boil:"health" json:"health" toml:"health" yaml:"health"`
	HealthNote       string            `boil:"health_note" json:"health_note" toml:"health_note" yaml:"health_note"`
	HealthCheckedAt  null.Time         `boil:"health_checked_at" json:"health_checked_at,omitempty" toml:"health_checked_at" yaml:"health_checked_at,omitempty"`
	NamingPattern    string            `boil:"naming_pattern" json:"naming_pattern" toml:"naming_pattern" yaml:"naming_pattern"`
	AnnounceChannel  string            `boil:"announce_channel" json:"announce_channel" toml:"announce_channel" yaml:"announce_channel"`
	ArchiveOnResolve bool              `boil:"archive_on_resolve" json:"archive_on_resolve" toml:"archive_on_resolve" yaml:"archive_on_resolve"`
	ConnectedBy      null.String       `boil:"connected_by" json:"connected_by,omitempty" toml:"connected_by" yaml:"connected_by,omitempty"`
	CreatedAt        time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt        time.Time         `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *chatConnectionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chatConnectionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChatConnectionColumns = struct {
	ID               string
	WorkspaceID      string
	Provider         string
	ExternalID       string
	ExternalName     string
	BotUserID        string
	BotTokenEnc      string
	AppID            string
	TenantID         string
	ServiceURL       string
	HookTokenHash    string
	HookSecretEnc    string
	Scopes           string
	Enabled          string
	Health           string
	HealthNote       string
	HealthCheckedAt  string
	NamingPattern    string
	AnnounceChannel  string
	ArchiveOnResolve string
	ConnectedBy      string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "id",
	WorkspaceID:      "workspace_id",
	Provider:         "provider",
	ExternalID:       "external_id",
	ExternalName:     "external_name",
	BotUserID:        "bot_user_id",
	BotTokenEnc:      "bot_token_enc",
	AppID:            "app_id",
	TenantID:         "tenant_id",
	ServiceURL:       "service_url",
	HookTokenHash:    "hook_token_hash",
	HookSecretEnc:    "hook_secret_enc",
	Scopes:           "scopes",
	Enabled:          "enabled",
	Health:           "health",
	HealthNote:       "health_note",
	HealthCheckedAt:  "health_checked_at",
	NamingPattern:    "naming_pattern",
	AnnounceChannel:  "announce_channel",
	ArchiveOnResolve: "archive_on_resolve",
	ConnectedBy:      "connected_by",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

var ChatConnectionTableColumns = struct {
	ID               string
	WorkspaceID      string
	Provider         string
	ExternalID       string
	ExternalName     string
	BotUserID        string
	BotTokenEnc      string
	AppID            string
	TenantID         string
	ServiceURL       string
	HookTokenHash    string
	HookSecretEnc    string
	Scopes           string
	Enabled          string
	Health           string
	HealthNote       string
	HealthCheckedAt  string
	NamingPattern    string
	AnnounceChannel  string
	ArchiveOnResolve string
	ConnectedBy      string
	CreatedAt        string
	UpdatedAt        string
}{
	ID:               "chat_connections.id",
	WorkspaceID:      "chat_connections.workspace_id",
	Provider:         "chat_connections.provider",
	ExternalID:       "chat_connections.external_id",
	ExternalName:     "chat_connections.external_name",
	BotUserID:        "chat_connections.bot_user_id",
	BotTokenEnc:      "chat_connections.bot_token_enc",
	AppID:            "chat_connections.app_id",
	TenantID:         "chat_connections.tenant_id",
	ServiceURL:       "chat_connections.service_url",
	HookTokenHash:    "chat_connections.hook_token_hash",
	HookSecretEnc:    "chat_connections.hook_secret_enc",
	Scopes:           "chat_connections.scopes",
	Enabled:          "chat_connections.enabled",
	Health:           "chat_connections.health",
	HealthNote:       "chat_connections.health_note",
	HealthCheckedAt:  "chat_connections.health_checked_at",
	NamingPattern:    "chat_connections.naming_pattern",
	AnnounceChannel:  "chat_connections.announce_channel",
	ArchiveOnResolve: "chat_connections.archive_on_resolve",
	ConnectedBy:      "chat_connections.connected_by",
	CreatedAt:        "chat_connections.created_at",
	UpdatedAt:        "chat_connections.updated_at",
}

// Generated where

type whereHelpernull_Bytes struct{ field string }

func (w whereHelpernull_Bytes) EQ(x null.Bytes) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Bytes) NEQ(x null.Bytes) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Bytes) LT(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Bytes) LTE(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Bytes) GT(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Bytes) GTE(x null.Bytes) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Bytes) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Bytes) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ChatConnectionWhere = struct {
	ID               whereHelperstring
	WorkspaceID      whereHelperstring
	Provider         whereHelperstring
	ExternalID       whereHelperstring
	ExternalName     whereHelperstring
	BotUserID        whereHelperstring
	BotTokenEnc      whereHelpernull_Bytes
	AppID            whereHelperstring
	TenantID         whereHelperstring
	ServiceURL       whereHelperstring
	HookTokenHash    whereHelpernull_String
	HookSecretEnc    whereHelpernull_Bytes
	Scopes           whereHelpertypes_StringArray
	Enabled          whereHelperbool
	Health           whereHelperstring
	HealthNote       whereHelperstring
	HealthCheckedAt  whereHelpernull_Time
	NamingPattern    whereHelperstring
	AnnounceChannel  whereHelperstring
	ArchiveOnResolve whereHelperbool
	ConnectedBy      whereHelpernull_String
	CreatedAt        whereHelpertime_Time
	UpdatedAt        whereHelpertime_Time
}{
	ID:               whereHelperstring{field: "\"chat_connections\".\"id\""},
	WorkspaceID:      whereHelperstring{field: "\"chat_connections\".\"workspace_id\""},
	Provider:         whereHelperstring{field: "\"chat_connections\".\"provider\""},
	ExternalID:       whereHelperstring{field: "\"chat_connections\".\"external_id\""},
	ExternalName:     whereHelperstring{field: "\"chat_connections\".\"external_name\""},
	BotUserID:        whereHelperstring{field: "\"chat_connections\".\"bot_user_id\""},
	BotTokenEnc:      whereHelpernull_Bytes{field: "\"chat_connections\".\"bot_token_enc\""},
	AppID:            whereHelperstring{field: "\"chat_connections\".\"app_id\""},
	TenantID:         whereHelperstring{field: "\"chat_connections\".\"tenant_id\""},
	ServiceURL:       whereHelperstring{field: "\"chat_connections\".\"service_url\""},
	HookTokenHash:    whereHelpernull_String{field: "\"chat_connections\".\"hook_token_hash\""},
	HookSecretEnc:    whereHelpernull_Bytes{field: "\"chat_connections\".\"hook_secret_enc\""},
	Scopes:           whereHelpertypes_StringArray{field: "\"chat_connections\".\"scopes\""},
	Enabled:          whereHelperbool{field: "\"chat_connections\".\"enabled\""},
	Health:           whereHelperstring{field: "\"chat_connections\".\"health\""},
	HealthNote:       whereHelperstring{field: "\"chat_connections\".\"health_note\""},
	HealthCheckedAt:  whereHelpernull_Time{field: "\"chat_connections\".\"health_checked_at\""},
	NamingPattern:    whereHelperstring{field: "\"chat_connections\".\"naming_pattern\""},
	AnnounceChannel:  whereHelperstring{field: "\"chat_connections\".\"announce_channel\""},
	ArchiveOnResolve: whereHelperbool{field: "\"chat_connections\".\"archive_on_resolve\""},
	ConnectedBy:      whereHelpernull_String{field: "\"chat_connections\".\"connected_by\""},
	CreatedAt:        whereHelpertime_Time{field: "\"chat_connections\".\"created_at\""},
	UpdatedAt:        whereHelpertime_Time{field: "\"chat_connections\".\"updated_at\""},
}

// ChatConnectionRels is where relationship names are stored.
var ChatConnectionRels = struct {
	ConnectedByUser          string
	Workspace                string
	ConnectionChatIdentities string
}{
	ConnectedByUser:          "ConnectedByUser",
	Workspace:                "Workspace",
	ConnectionChatIdentities: "ConnectionChatIdentities",
}

// chatConnectionR is where relationships are stored.
type chatConnectionR struct {
	ConnectedByUser          *User             `boil:"ConnectedByUser" json:"ConnectedByUser" toml:"ConnectedByUser" yaml:"ConnectedByUser"`
	Workspace                *Workspace        `boil:"Workspace" json:"Workspace" toml:"Workspace" yaml:"Workspace"`
	ConnectionChatIdentities ChatIdentitySlice `boil:"ConnectionChatIdentities" json:"ConnectionChatIdentities" toml:"ConnectionChatIdentities" yaml:"ConnectionChatIdentities"`
}

// NewStruct creates a new relationship struct
func (*chatConnectionR) NewStruct() *chatConnectionR {
	return &chatConnectionR{}
}

func (o *ChatConnection) GetConnectedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetConnectedByUser()
}

func (r *chatConnectionR) GetConnectedByUser() *User {
	if r == nil {
		return nil
	}

	return r.ConnectedByUser
}

func (o *ChatConnection) GetWorkspace() *Workspace {
	if o == nil {
		return nil
	}

	return o.R.GetWorkspace()
}

func (r *chatConnectionR) GetWorkspace() *Workspace {
	if r == nil {
		return nil
	}

	return r.Workspace
}

func (o *ChatConnection) GetConnectionChatIdentities() ChatIdentitySlice {
	if o == nil {
		return nil
	}

	return o.R.GetConnectionChatIdentities()
}

func (r *chatConnectionR) GetConnectionChatIdentities() ChatIdentitySlice {
	if r == nil {
		return nil
	}

	return r.ConnectionChatIdentities
}

// chatConnectionL is where Load methods for each relationship are stored.
type chatConnectionL struct{}

var (
	chatConnectionAllColumns            = []string{"id", "workspace_id", "provider", "external_id", "external_name", "bot_user_id", "bot_token_enc", "app_id", "tenant_id", "service_url", "hook_token_hash", "hook_secret_enc", "scopes", "enabled", "health", "health_note", "health_checked_at", "naming_pattern", "announce_channel", "archive_on_resolve", "connected_by", "created_at", "updated_at"}
	chatConnectionColumnsWithoutDefault = []string{"workspace_id", "provider"}
	chatConnectionColumnsWithDefault    = []string{"id", "external_id", "external_name", "bot_user_id", "bot_token_enc", "app_id", "tenant_id", "service_url", "hook_token_hash", "hook_secret_enc", "scopes", "enabled", "health", "health_note", "health_checked_at", "naming_pattern", "announce_channel", "archive_on_resolve", "connected_by", "created_at", "updated_at"}
	chatConnectionPrimaryKeyColumns     = []string{"id"}
	chatConnectionGeneratedColumns      = []string{}
)

type (
	// ChatConnectionSlice is an alias for a slice of pointers to ChatConnection.
	// This should almost always be used instead of []ChatConnection.
	ChatConnectionSlice []*ChatConnection
	// ChatConnectionHook is the signature for custom ChatConnection hook methods
	ChatConnectionHook func(context.Context, boil.ContextExecutor, *ChatConnection) error

	chatConnectionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chatConnectionType                 = reflect.TypeOf(&ChatConnection{})
	chatConnectionMapping              = queries.MakeStructMapping(chatConnectionType)
	chatConnectionPrimaryKeyMapping, _ = queries.BindMapping(chatConnectionType, chatConnectionMapping, chatConnectionPrimaryKeyColumns)
	chatConnectionInsertCacheMut       sync.RWMutex
	chatConnectionInsertCache          = make(map[string]insertCache)
	chatConnectionUpdateCacheMut       sync.RWMutex
	chatConnectionUpdateCache          = make(map[string]updateCache)
	chatConnectionUpsertCacheMut       sync.RWMutex
	chatConnectionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var chatConnectionAfterSelectMu sync.Mutex
var chatConnectionAfterSelectHooks []ChatConnectionHook

var chatConnectionBeforeInsertMu sync.Mutex
var chatConnectionBeforeInsertHooks []ChatConnectionHook
var chatConnectionAfterInsertMu sync.Mutex
var chatConnectionAfterInsertHooks []ChatConnectionHook

var chatConnectionBeforeUpdateMu sync.Mutex
var chatConnectionBeforeUpdateHooks []ChatConnectionHook
var chatConnectionAfterUpdateMu sync.Mutex
var chatConnectionAfterUpdateHooks []ChatConnectionHook

var chatConnectionBeforeDeleteMu sync.Mutex
var chatConnectionBeforeDeleteHooks []ChatConnectionHook
var chatConnectionAfterDeleteMu sync.Mutex
var chatConnectionAfterDeleteHooks []ChatConnectionHook

var chatConnectionBeforeUpsertMu sync.Mutex
var chatConnectionBeforeUpsertHooks []ChatConnectionHook
var chatConnectionAfterUpsertMu sync.Mutex
var chatConnectionAfterUpsertHooks []ChatConnectionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChatConnection) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChatConnection) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChatConnection) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChatConnection) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChatConnection) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChatConnection) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChatConnection) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChatConnection) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChatConnection) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range chatConnectionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChatConnectionHook registers your hook function for all future operations.
func AddChatConnectionHook(hookPoint boil.HookPoint, chatConnectionHook ChatConnectionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		chatConnectionAfterSelectMu.Lock()
		chatConnectionAfterSelectHooks = append(chatConnectionAfterSelectHooks, chatConnectionHook)
		chatConnectionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		chatConnectionBeforeInsertMu.Lock()
		chatConnectionBeforeInsertHooks = append(chatConnectionBeforeInsertHooks, chatConnectionHook)
		chatConnectionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		chatConnectionAfterInsertMu.Lock()
		chatConnectionAfterInsertHooks = append(chatConnectionAfterInsertHooks, chatConnectionHook)
		chatConnectionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		chatConnectionBeforeUpdateMu.Lock()
		chatConnectionBeforeUpdateHooks = append(chatConnectionBeforeUpdateHooks, chatConnectionHook)
		chatConnectionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		chatConnectionAfterUpdateMu.Lock()
		chatConnectionAfterUpdateHooks = append(chatConnectionAfterUpdateHooks, chatConnectionHook)
		chatConnectionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		chatConnectionBeforeDeleteMu.Lock()
		chatConnectionBeforeDeleteHooks = append(chatConnectionBeforeDeleteHooks, chatConnectionHook)
		chatConnectionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		chatConnectionAfterDeleteMu.Lock()
		chatConnectionAfterDeleteHooks = append(chatConnectionAfterDeleteHooks, chatConnectionHook)
		chatConnectionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		chatConnectionBeforeUpsertMu.Lock()
		chatConnectionBeforeUpsertHooks = append(chatConnectionBeforeUpsertHooks, chatConnectionHook)
		chatConnectionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		chatConnectionAfterUpsertMu.Lock()
		chatConnectionAfterUpsertHooks = append(chatConnectionAfterUpsertHooks, chatConnectionHook)
		chatConnectionAfterUpsertMu.Unlock()
	}
}

// One returns a single chatConnection record from the query.
func (q chatConnectionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChatConnection, error) {
	o := &ChatConnection{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for chat_connections")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChatConnection records from the query.
func (q chatConnectionQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChatConnectionSlice, error) {
	var o []*ChatConnection

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to ChatConnection slice")
	}

	if len(chatConnectionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChatConnection records in the query.
func (q chatConnectionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count chat_connections rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chatConnectionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if chat_connections exists")
	}

	return count > 0, nil
}

// ConnectedByUser pointed to by the foreign key.
func (o *ChatConnection) ConnectedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ConnectedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Workspace pointed to by the foreign key.
func (o *ChatConnection) Workspace(mods ...qm.QueryMod) workspaceQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkspaceID),
	}

	queryMods = append(queryMods, mods...)

	return Workspaces(queryMods...)
}

// ConnectionChatIdentities retrieves all the chat_identity's ChatIdentities with an executor via connection_id column.
func (o *ChatConnection) ConnectionChatIdentities(mods ...qm.QueryMod) chatIdentityQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"chat_identities\".\"connection_id\"=?", o.ID),
	)

	return ChatIdentities(queryMods...)
}

// LoadConnectedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (chatConnectionL) LoadConnectedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChatConnection any, mods queries.Applicator) error {
	var slice []*ChatConnection
	var object *ChatConnection

	if singular {
		var ok bool
		object, ok = maybeChatConnection.(*ChatConnection)
		if !ok {
			object = new(ChatConnection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChatConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChatConnection))
			}
		}
	} else {
		s, ok := maybeChatConnection.(*[]*ChatConnection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChatConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChatConnection))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &chatConnectionR{}
		}
		if !queries.IsNil(object.ConnectedBy) {
			args[object.ConnectedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chatConnectionR{}
			}

			if !queries.IsNil(obj.ConnectedBy) {
				args[obj.ConnectedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ConnectedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ConnectedByChatConnections = append(foreign.R.ConnectedByChatConnections, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ConnectedBy, foreign.ID) {
				local.R.ConnectedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ConnectedByChatConnections = append(foreign.R.ConnectedByChatConnections, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkspace allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (chatConnectionL) LoadWorkspace(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChatConnection any, mods queries.Applicator) error {
	var slice []*ChatConnection
	var object *ChatConnection

	if singular {
		var ok bool
		object, ok = maybeChatConnection.(*ChatConnection)
		if !ok {
			object = new(ChatConnection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChatConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChatConnection))
			}
		}
	} else {
		s, ok := maybeChatConnection.(*[]*ChatConnection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChatConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChatConnection))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &chatConnectionR{}
		}
		args[object.WorkspaceID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chatConnectionR{}
			}

			args[obj.WorkspaceID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`workspaces`),
		qm.WhereIn(`workspaces.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Workspace")
	}

	var resultSlice []*Workspace
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Workspace")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for workspaces")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for workspaces")
	}

	if len(workspaceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Workspace = foreign
		if foreign.R == nil {
			foreign.R = &workspaceR{}
		}
		foreign.R.ChatConnections = append(foreign.R.ChatConnections, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkspaceID == foreign.ID {
				local.R.Workspace = foreign
				if foreign.R == nil {
					foreign.R = &workspaceR{}
				}
				foreign.R.ChatConnections = append(foreign.R.ChatConnections, local)
				break
			}
		}
	}

	return nil
}

// LoadConnectionChatIdentities allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (chatConnectionL) LoadConnectionChatIdentities(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChatConnection any, mods queries.Applicator) error {
	var slice []*ChatConnection
	var object *ChatConnection

	if singular {
		var ok bool
		object, ok = maybeChatConnection.(*ChatConnection)
		if !ok {
			object = new(ChatConnection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChatConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChatConnection))
			}
		}
	} else {
		s, ok := maybeChatConnection.(*[]*ChatConnection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChatConnection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChatConnection))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &chatConnectionR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chatConnectionR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`chat_identities`),
		qm.WhereIn(`chat_identities.connection_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load chat_identities")
	}

	var resultSlice []*ChatIdentity
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice chat_identities")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on chat_identities")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chat_identities")
	}

	if len(chatIdentityAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ConnectionChatIdentities = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &chatIdentityR{}
			}
			foreign.R.Connection = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ConnectionID {
				local.R.ConnectionChatIdentities = append(local.R.ConnectionChatIdentities, foreign)
				if foreign.R == nil {
					foreign.R = &chatIdentityR{}
				}
				foreign.R.Connection = local
				break
			}
		}
	}

	return nil
}

// SetConnectedByUser of the chatConnection to the related item.
// Sets o.R.ConnectedByUser to related.
// Adds o to related.R.ConnectedByChatConnections.
func (o *ChatConnection) SetConnectedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chat_connections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"connected_by"}),
		strmangle.WhereClause("\"", "\"", 2, chatConnectionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ConnectedBy, related.ID)
	if o.R == nil {
		o.R = &chatConnectionR{
			ConnectedByUser: related,
		}
	} else {
		o.R.ConnectedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			ConnectedByChatConnections: ChatConnectionSlice{o},
		}
	} else {
		related.R.ConnectedByChatConnections = append(related.R.ConnectedByChatConnections, o)
	}

	return nil
}

// RemoveConnectedByUser relationship.
// Sets o.R.ConnectedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ChatConnection) RemoveConnectedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.ConnectedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("connected_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ConnectedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ConnectedByChatConnections {
		if queries.Equal(o.ConnectedBy, ri.ConnectedBy) {
			continue
		}

		ln := len(related.R.ConnectedByChatConnections)
		if ln > 1 && i < ln-1 {
			related.R.ConnectedByChatConnections[i] = related.R.ConnectedByChatConnections[ln-1]
		}
		related.R.ConnectedByChatConnections = related.R.ConnectedByChatConnections[:ln-1]
		break
	}
	return nil
}

// SetWorkspace of the chatConnection to the related item.
// Sets o.R.Workspace to related.
// Adds o to related.R.ChatConnections.
func (o *ChatConnection) SetWorkspace(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Workspace) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chat_connections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workspace_id"}),
		strmangle.WhereClause("\"", "\"", 2, chatConnectionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkspaceID = related.ID
	if o.R == nil {
		o.R = &chatConnectionR{
			Workspace: related,
		}
	} else {
		o.R.Workspace = related
	}

	if related.R == nil {
		related.R = &workspaceR{
			ChatConnections: ChatConnectionSlice{o},
		}
	} else {
		related.R.ChatConnections = append(related.R.ChatConnections, o)
	}

	return nil
}

// AddConnectionChatIdentities adds the given related objects to the existing relationships
// of the chat_connection, optionally inserting them as new records.
// Appends related to o.R.ConnectionChatIdentities.
// Sets related.R.Connection appropriately.
func (o *ChatConnection) AddConnectionChatIdentities(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ChatIdentity) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ConnectionID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"chat_identities\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"connection_id"}),
				strmangle.WhereClause("\"", "\"", 2, chatIdentityPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ConnectionID = o.ID
		}
	}

	if o.R == nil {
		o.R = &chatConnectionR{
			ConnectionChatIdentities: related,
		}
	} else {
		o.R.ConnectionChatIdentities = append(o.R.ConnectionChatIdentities, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &chatIdentityR{
				Connection: o,
			}
		} else {
			rel.R.Connection = o
		}
	}
	return nil
}

// ChatConnections retrieves all the records using an executor.
func ChatConnections(mods ...qm.QueryMod) chatConnectionQuery {
	mods = append(mods, qm.From("\"chat_connections\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"chat_connections\".*"})
	}

	return chatConnectionQuery{q}
}

// FindChatConnection retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChatConnection(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ChatConnection, error) {
	chatConnectionObj := &ChatConnection{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"chat_connections\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, chatConnectionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from chat_connections")
	}

	if err = chatConnectionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return chatConnectionObj, err
	}

	return chatConnectionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChatConnection) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no chat_connections provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chatConnectionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chatConnectionInsertCacheMut.RLock()
	cache, cached := chatConnectionInsertCache[key]
	chatConnectionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chatConnectionAllColumns,
			chatConnectionColumnsWithDefault,
			chatConnectionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chatConnectionType, chatConnectionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chatConnectionType, chatConnectionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"chat_connections\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"chat_connections\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into chat_connections")
	}

	if !cached {
		chatConnectionInsertCacheMut.Lock()
		chatConnectionInsertCache[key] = cache
		chatConnectionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChatConnection.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChatConnection) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	chatConnectionUpdateCacheMut.RLock()
	cache, cached := chatConnectionUpdateCache[key]
	chatConnectionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chatConnectionAllColumns,
			chatConnectionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update chat_connections, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"chat_connections\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chatConnectionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chatConnectionType, chatConnectionMapping, append(wl, chatConnectionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update chat_connections row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for chat_connections")
	}

	if !cached {
		chatConnectionUpdateCacheMut.Lock()
		chatConnectionUpdateCache[key] = cache
		chatConnectionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q chatConnectionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for chat_connections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for chat_connections")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChatConnectionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chatConnectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"chat_connections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chatConnectionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in chatConnection slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all chatConnection")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChatConnection) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no chat_connections provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(chatConnectionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chatConnectionUpsertCacheMut.RLock()
	cache, cached := chatConnectionUpsertCache[key]
	chatConnectionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			chatConnectionAllColumns,
			chatConnectionColumnsWithDefault,
			chatConnectionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			chatConnectionAllColumns,
			chatConnectionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert chat_connections, could not build update column list")
		}

		ret := strmangle.SetComplement(chatConnectionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(chatConnectionPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert chat_connections, could not build conflict column list")
			}

			conflict = make([]string, len(chatConnectionPrimaryKeyColumns))
			copy(conflict, chatConnectionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"chat_connections\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(chatConnectionType, chatConnectionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chatConnectionType, chatConnectionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert chat_connections")
	}

	if !cached {
		chatConnectionUpsertCacheMut.Lock()
		chatConnectionUpsertCache[key] = cache
		chatConnectionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChatConnection record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChatConnection) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no ChatConnection provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chatConnectionPrimaryKeyMapping)
	sql := "DELETE FROM \"chat_connections\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from chat_connections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for chat_connections")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chatConnectionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no chatConnectionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from chat_connections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for chat_connections")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChatConnectionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(chatConnectionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chatConnectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"chat_connections\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chatConnectionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from chatConnection slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for chat_connections")
	}

	if len(chatConnectionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChatConnection) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChatConnection(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChatConnectionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChatConnectionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chatConnectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"chat_connections\".* FROM \"chat_connections\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chatConnectionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in ChatConnectionSlice")
	}

	*o = slice

	return nil
}

// ChatConnectionExists checks if the ChatConnection row exists.
func ChatConnectionExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"chat_connections\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if chat_connections exists")
	}

	return exists, nil
}

// Exists checks if the ChatConnection row exists.
func (o *ChatConnection) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChatConnectionExists(ctx, exec, o.ID)
}
