// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbpostgres

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ScheduleLayerParticipant is an object representing the database table.
type ScheduleLayerParticipant struct {
	LayerID     string    `boil:"layer_id" json:"layer_id" toml:"layer_id" yaml:"layer_id"`
	WorkspaceID string    `boil:"workspace_id" json:"workspace_id" toml:"workspace_id" yaml:"workspace_id"`
	UserID      string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Position    int       `boil:"position" json:"position" toml:"position" yaml:"position"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *scheduleLayerParticipantR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L scheduleLayerParticipantL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ScheduleLayerParticipantColumns = struct {
	LayerID     string
	WorkspaceID string
	UserID      string
	Position    string
	CreatedAt   string
}{
	LayerID:     "layer_id",
	WorkspaceID: "workspace_id",
	UserID:      "user_id",
	Position:    "position",
	CreatedAt:   "created_at",
}

var ScheduleLayerParticipantTableColumns = struct {
	LayerID     string
	WorkspaceID string
	UserID      string
	Position    string
	CreatedAt   string
}{
	LayerID:     "schedule_layer_participants.layer_id",
	WorkspaceID: "schedule_layer_participants.workspace_id",
	UserID:      "schedule_layer_participants.user_id",
	Position:    "schedule_layer_participants.position",
	CreatedAt:   "schedule_layer_participants.created_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ScheduleLayerParticipantWhere = struct {
	LayerID     whereHelperstring
	WorkspaceID whereHelperstring
	UserID      whereHelperstring
	Position    whereHelperint
	CreatedAt   whereHelpertime_Time
}{
	LayerID:     whereHelperstring{field: "\"schedule_layer_participants\".\"layer_id\""},
	WorkspaceID: whereHelperstring{field: "\"schedule_layer_participants\".\"workspace_id\""},
	UserID:      whereHelperstring{field: "\"schedule_layer_participants\".\"user_id\""},
	Position:    whereHelperint{field: "\"schedule_layer_participants\".\"position\""},
	CreatedAt:   whereHelpertime_Time{field: "\"schedule_layer_participants\".\"created_at\""},
}

// ScheduleLayerParticipantRels is where relationship names are stored.
var ScheduleLayerParticipantRels = struct {
}{}

// scheduleLayerParticipantR is where relationships are stored.
type scheduleLayerParticipantR struct {
}

// NewStruct creates a new relationship struct
func (*scheduleLayerParticipantR) NewStruct() *scheduleLayerParticipantR {
	return &scheduleLayerParticipantR{}
}

// scheduleLayerParticipantL is where Load methods for each relationship are stored.
type scheduleLayerParticipantL struct{}

var (
	scheduleLayerParticipantAllColumns            = []string{"layer_id", "workspace_id", "user_id", "position", "created_at"}
	scheduleLayerParticipantColumnsWithoutDefault = []string{"layer_id", "workspace_id", "user_id", "position"}
	scheduleLayerParticipantColumnsWithDefault    = []string{"created_at"}
	scheduleLayerParticipantPrimaryKeyColumns     = []string{"layer_id", "user_id"}
	scheduleLayerParticipantGeneratedColumns      = []string{}
)

type (
	// ScheduleLayerParticipantSlice is an alias for a slice of pointers to ScheduleLayerParticipant.
	// This should almost always be used instead of []ScheduleLayerParticipant.
	ScheduleLayerParticipantSlice []*ScheduleLayerParticipant
	// ScheduleLayerParticipantHook is the signature for custom ScheduleLayerParticipant hook methods
	ScheduleLayerParticipantHook func(context.Context, boil.ContextExecutor, *ScheduleLayerParticipant) error

	scheduleLayerParticipantQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	scheduleLayerParticipantType                 = reflect.TypeOf(&ScheduleLayerParticipant{})
	scheduleLayerParticipantMapping              = queries.MakeStructMapping(scheduleLayerParticipantType)
	scheduleLayerParticipantPrimaryKeyMapping, _ = queries.BindMapping(scheduleLayerParticipantType, scheduleLayerParticipantMapping, scheduleLayerParticipantPrimaryKeyColumns)
	scheduleLayerParticipantInsertCacheMut       sync.RWMutex
	scheduleLayerParticipantInsertCache          = make(map[string]insertCache)
	scheduleLayerParticipantUpdateCacheMut       sync.RWMutex
	scheduleLayerParticipantUpdateCache          = make(map[string]updateCache)
	scheduleLayerParticipantUpsertCacheMut       sync.RWMutex
	scheduleLayerParticipantUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var scheduleLayerParticipantAfterSelectMu sync.Mutex
var scheduleLayerParticipantAfterSelectHooks []ScheduleLayerParticipantHook

var scheduleLayerParticipantBeforeInsertMu sync.Mutex
var scheduleLayerParticipantBeforeInsertHooks []ScheduleLayerParticipantHook
var scheduleLayerParticipantAfterInsertMu sync.Mutex
var scheduleLayerParticipantAfterInsertHooks []ScheduleLayerParticipantHook

var scheduleLayerParticipantBeforeUpdateMu sync.Mutex
var scheduleLayerParticipantBeforeUpdateHooks []ScheduleLayerParticipantHook
var scheduleLayerParticipantAfterUpdateMu sync.Mutex
var scheduleLayerParticipantAfterUpdateHooks []ScheduleLayerParticipantHook

var scheduleLayerParticipantBeforeDeleteMu sync.Mutex
var scheduleLayerParticipantBeforeDeleteHooks []ScheduleLayerParticipantHook
var scheduleLayerParticipantAfterDeleteMu sync.Mutex
var scheduleLayerParticipantAfterDeleteHooks []ScheduleLayerParticipantHook

var scheduleLayerParticipantBeforeUpsertMu sync.Mutex
var scheduleLayerParticipantBeforeUpsertHooks []ScheduleLayerParticipantHook
var scheduleLayerParticipantAfterUpsertMu sync.Mutex
var scheduleLayerParticipantAfterUpsertHooks []ScheduleLayerParticipantHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ScheduleLayerParticipant) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ScheduleLayerParticipant) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ScheduleLayerParticipant) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ScheduleLayerParticipant) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ScheduleLayerParticipant) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ScheduleLayerParticipant) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ScheduleLayerParticipant) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ScheduleLayerParticipant) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ScheduleLayerParticipant) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduleLayerParticipantAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddScheduleLayerParticipantHook registers your hook function for all future operations.
func AddScheduleLayerParticipantHook(hookPoint boil.HookPoint, scheduleLayerParticipantHook ScheduleLayerParticipantHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		scheduleLayerParticipantAfterSelectMu.Lock()
		scheduleLayerParticipantAfterSelectHooks = append(scheduleLayerParticipantAfterSelectHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		scheduleLayerParticipantBeforeInsertMu.Lock()
		scheduleLayerParticipantBeforeInsertHooks = append(scheduleLayerParticipantBeforeInsertHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		scheduleLayerParticipantAfterInsertMu.Lock()
		scheduleLayerParticipantAfterInsertHooks = append(scheduleLayerParticipantAfterInsertHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		scheduleLayerParticipantBeforeUpdateMu.Lock()
		scheduleLayerParticipantBeforeUpdateHooks = append(scheduleLayerParticipantBeforeUpdateHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		scheduleLayerParticipantAfterUpdateMu.Lock()
		scheduleLayerParticipantAfterUpdateHooks = append(scheduleLayerParticipantAfterUpdateHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		scheduleLayerParticipantBeforeDeleteMu.Lock()
		scheduleLayerParticipantBeforeDeleteHooks = append(scheduleLayerParticipantBeforeDeleteHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		scheduleLayerParticipantAfterDeleteMu.Lock()
		scheduleLayerParticipantAfterDeleteHooks = append(scheduleLayerParticipantAfterDeleteHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		scheduleLayerParticipantBeforeUpsertMu.Lock()
		scheduleLayerParticipantBeforeUpsertHooks = append(scheduleLayerParticipantBeforeUpsertHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		scheduleLayerParticipantAfterUpsertMu.Lock()
		scheduleLayerParticipantAfterUpsertHooks = append(scheduleLayerParticipantAfterUpsertHooks, scheduleLayerParticipantHook)
		scheduleLayerParticipantAfterUpsertMu.Unlock()
	}
}

// One returns a single scheduleLayerParticipant record from the query.
func (q scheduleLayerParticipantQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ScheduleLayerParticipant, error) {
	o := &ScheduleLayerParticipant{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: failed to execute a one query for schedule_layer_participants")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ScheduleLayerParticipant records from the query.
func (q scheduleLayerParticipantQuery) All(ctx context.Context, exec boil.ContextExecutor) (ScheduleLayerParticipantSlice, error) {
	var o []*ScheduleLayerParticipant

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbpostgres: failed to assign all query results to ScheduleLayerParticipant slice")
	}

	if len(scheduleLayerParticipantAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ScheduleLayerParticipant records in the query.
func (q scheduleLayerParticipantQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to count schedule_layer_participants rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q scheduleLayerParticipantQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: failed to check if schedule_layer_participants exists")
	}

	return count > 0, nil
}

// ScheduleLayerParticipants retrieves all the records using an executor.
func ScheduleLayerParticipants(mods ...qm.QueryMod) scheduleLayerParticipantQuery {
	mods = append(mods, qm.From("\"schedule_layer_participants\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"schedule_layer_participants\".*"})
	}

	return scheduleLayerParticipantQuery{q}
}

// FindScheduleLayerParticipant retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindScheduleLayerParticipant(ctx context.Context, exec boil.ContextExecutor, layerID string, userID string, selectCols ...string) (*ScheduleLayerParticipant, error) {
	scheduleLayerParticipantObj := &ScheduleLayerParticipant{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"schedule_layer_participants\" where \"layer_id\"=$1 AND \"user_id\"=$2", sel,
	)

	q := queries.Raw(query, layerID, userID)

	err := q.Bind(ctx, exec, scheduleLayerParticipantObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbpostgres: unable to select from schedule_layer_participants")
	}

	if err = scheduleLayerParticipantObj.doAfterSelectHooks(ctx, exec); err != nil {
		return scheduleLayerParticipantObj, err
	}

	return scheduleLayerParticipantObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ScheduleLayerParticipant) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbpostgres: no schedule_layer_participants provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduleLayerParticipantColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	scheduleLayerParticipantInsertCacheMut.RLock()
	cache, cached := scheduleLayerParticipantInsertCache[key]
	scheduleLayerParticipantInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			scheduleLayerParticipantAllColumns,
			scheduleLayerParticipantColumnsWithDefault,
			scheduleLayerParticipantColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(scheduleLayerParticipantType, scheduleLayerParticipantMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(scheduleLayerParticipantType, scheduleLayerParticipantMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"schedule_layer_participants\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"schedule_layer_participants\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to insert into schedule_layer_participants")
	}

	if !cached {
		scheduleLayerParticipantInsertCacheMut.Lock()
		scheduleLayerParticipantInsertCache[key] = cache
		scheduleLayerParticipantInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ScheduleLayerParticipant.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ScheduleLayerParticipant) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	scheduleLayerParticipantUpdateCacheMut.RLock()
	cache, cached := scheduleLayerParticipantUpdateCache[key]
	scheduleLayerParticipantUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			scheduleLayerParticipantAllColumns,
			scheduleLayerParticipantPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbpostgres: unable to update schedule_layer_participants, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"schedule_layer_participants\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, scheduleLayerParticipantPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(scheduleLayerParticipantType, scheduleLayerParticipantMapping, append(wl, scheduleLayerParticipantPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update schedule_layer_participants row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by update for schedule_layer_participants")
	}

	if !cached {
		scheduleLayerParticipantUpdateCacheMut.Lock()
		scheduleLayerParticipantUpdateCache[key] = cache
		scheduleLayerParticipantUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q scheduleLayerParticipantQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all for schedule_layer_participants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected for schedule_layer_participants")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ScheduleLayerParticipantSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbpostgres: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduleLayerParticipantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"schedule_layer_participants\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, scheduleLayerParticipantPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to update all in scheduleLayerParticipant slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to retrieve rows affected all in update all scheduleLayerParticipant")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ScheduleLayerParticipant) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbpostgres: no schedule_layer_participants provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduleLayerParticipantColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	scheduleLayerParticipantUpsertCacheMut.RLock()
	cache, cached := scheduleLayerParticipantUpsertCache[key]
	scheduleLayerParticipantUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			scheduleLayerParticipantAllColumns,
			scheduleLayerParticipantColumnsWithDefault,
			scheduleLayerParticipantColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			scheduleLayerParticipantAllColumns,
			scheduleLayerParticipantPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbpostgres: unable to upsert schedule_layer_participants, could not build update column list")
		}

		ret := strmangle.SetComplement(scheduleLayerParticipantAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(scheduleLayerParticipantPrimaryKeyColumns) == 0 {
				return errors.New("dbpostgres: unable to upsert schedule_layer_participants, could not build conflict column list")
			}

			conflict = make([]string, len(scheduleLayerParticipantPrimaryKeyColumns))
			copy(conflict, scheduleLayerParticipantPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"schedule_layer_participants\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(scheduleLayerParticipantType, scheduleLayerParticipantMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(scheduleLayerParticipantType, scheduleLayerParticipantMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to upsert schedule_layer_participants")
	}

	if !cached {
		scheduleLayerParticipantUpsertCacheMut.Lock()
		scheduleLayerParticipantUpsertCache[key] = cache
		scheduleLayerParticipantUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ScheduleLayerParticipant record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ScheduleLayerParticipant) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbpostgres: no ScheduleLayerParticipant provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), scheduleLayerParticipantPrimaryKeyMapping)
	sql := "DELETE FROM \"schedule_layer_participants\" WHERE \"layer_id\"=$1 AND \"user_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete from schedule_layer_participants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by delete for schedule_layer_participants")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q scheduleLayerParticipantQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbpostgres: no scheduleLayerParticipantQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from schedule_layer_participants")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for schedule_layer_participants")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ScheduleLayerParticipantSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(scheduleLayerParticipantBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduleLayerParticipantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"schedule_layer_participants\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scheduleLayerParticipantPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: unable to delete all from scheduleLayerParticipant slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbpostgres: failed to get rows affected by deleteall for schedule_layer_participants")
	}

	if len(scheduleLayerParticipantAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ScheduleLayerParticipant) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindScheduleLayerParticipant(ctx, exec, o.LayerID, o.UserID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ScheduleLayerParticipantSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ScheduleLayerParticipantSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduleLayerParticipantPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"schedule_layer_participants\".* FROM \"schedule_layer_participants\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, scheduleLayerParticipantPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbpostgres: unable to reload all in ScheduleLayerParticipantSlice")
	}

	*o = slice

	return nil
}

// ScheduleLayerParticipantExists checks if the ScheduleLayerParticipant row exists.
func ScheduleLayerParticipantExists(ctx context.Context, exec boil.ContextExecutor, layerID string, userID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"schedule_layer_participants\" where \"layer_id\"=$1 AND \"user_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, layerID, userID)
	}
	row := exec.QueryRowContext(ctx, sql, layerID, userID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbpostgres: unable to check if schedule_layer_participants exists")
	}

	return exists, nil
}

// Exists checks if the ScheduleLayerParticipant row exists.
func (o *ScheduleLayerParticipant) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ScheduleLayerParticipantExists(ctx, exec, o.LayerID, o.UserID)
}
