// Code generated by MockGen. DO NOT EDIT.
// Source: chat_courier.go
//
// Generated by this command:
//
//	mockgen -source=chat_courier.go -destination=./chat_courier/chat_courier_mock.go -package=chat_courier
//

// Package chat_courier is a generated GoMock package.
package chat_courier

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockChatCourier is a mock of ChatCourier interface.
type MockChatCourier struct {
	ctrl     *gomock.Controller
	recorder *MockChatCourierMockRecorder
	isgomock struct{}
}

// MockChatCourierMockRecorder is the mock recorder for MockChatCourier.
type MockChatCourierMockRecorder struct {
	mock *MockChatCourier
}

// NewMockChatCourier creates a new mock instance.
func NewMockChatCourier(ctrl *gomock.Controller) *MockChatCourier {
	mock := &MockChatCourier{ctrl: ctrl}
	mock.recorder = &MockChatCourierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatCourier) EXPECT() *MockChatCourierMockRecorder {
	return m.recorder
}

// AnswerCallback mocks base method.
func (m *MockChatCourier) AnswerCallback(ctx context.Context, provider entity.ChatProvider, token, callbackID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnswerCallback", ctx, provider, token, callbackID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnswerCallback indicates an expected call of AnswerCallback.
func (mr *MockChatCourierMockRecorder) AnswerCallback(ctx, provider, token, callbackID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnswerCallback", reflect.TypeOf((*MockChatCourier)(nil).AnswerCallback), ctx, provider, token, callbackID, text)
}

// AuthorizeURL mocks base method.
func (m *MockChatCourier) AuthorizeURL(ctx context.Context, provider entity.ChatProvider, scopes []string, redirectURI, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorizeURL", ctx, provider, scopes, redirectURI, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthorizeURL indicates an expected call of AuthorizeURL.
func (mr *MockChatCourierMockRecorder) AuthorizeURL(ctx, provider, scopes, redirectURI, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorizeURL", reflect.TypeOf((*MockChatCourier)(nil).AuthorizeURL), ctx, provider, scopes, redirectURI, state)
}

// ExchangeIdentity mocks base method.
func (m *MockChatCourier) ExchangeIdentity(ctx context.Context, provider entity.ChatProvider, code, redirectURI string) (entity.ChatIdentityResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeIdentity", ctx, provider, code, redirectURI)
	ret0, _ := ret[0].(entity.ChatIdentityResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeIdentity indicates an expected call of ExchangeIdentity.
func (mr *MockChatCourierMockRecorder) ExchangeIdentity(ctx, provider, code, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeIdentity", reflect.TypeOf((*MockChatCourier)(nil).ExchangeIdentity), ctx, provider, code, redirectURI)
}

// ExchangeOAuth mocks base method.
func (m *MockChatCourier) ExchangeOAuth(ctx context.Context, provider entity.ChatProvider, code, redirectURI string) (entity.ChatOAuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeOAuth", ctx, provider, code, redirectURI)
	ret0, _ := ret[0].(entity.ChatOAuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeOAuth indicates an expected call of ExchangeOAuth.
func (mr *MockChatCourierMockRecorder) ExchangeOAuth(ctx, provider, code, redirectURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeOAuth", reflect.TypeOf((*MockChatCourier)(nil).ExchangeOAuth), ctx, provider, code, redirectURI)
}

// IdentityAuthorizeURL mocks base method.
func (m *MockChatCourier) IdentityAuthorizeURL(ctx context.Context, provider entity.ChatProvider, scopes []string, redirectURI, state, teamID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityAuthorizeURL", ctx, provider, scopes, redirectURI, state, teamID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityAuthorizeURL indicates an expected call of IdentityAuthorizeURL.
func (mr *MockChatCourierMockRecorder) IdentityAuthorizeURL(ctx, provider, scopes, redirectURI, state, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityAuthorizeURL", reflect.TypeOf((*MockChatCourier)(nil).IdentityAuthorizeURL), ctx, provider, scopes, redirectURI, state, teamID)
}

// LookupUser mocks base method.
func (m *MockChatCourier) LookupUser(ctx context.Context, provider entity.ChatProvider, token, externalID, email string) (entity.ChatUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupUser", ctx, provider, token, externalID, email)
	ret0, _ := ret[0].(entity.ChatUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupUser indicates an expected call of LookupUser.
func (mr *MockChatCourierMockRecorder) LookupUser(ctx, provider, token, externalID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupUser", reflect.TypeOf((*MockChatCourier)(nil).LookupUser), ctx, provider, token, externalID, email)
}

// Send mocks base method.
func (m *MockChatCourier) Send(ctx context.Context, in entity.ChatDelivery) (entity.ChatSendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, in)
	ret0, _ := ret[0].(entity.ChatSendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockChatCourierMockRecorder) Send(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockChatCourier)(nil).Send), ctx, in)
}

// SendToChannel mocks base method.
func (m *MockChatCourier) SendToChannel(ctx context.Context, provider entity.ChatProvider, token, guildID, channel, text string) (entity.ChatSendResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToChannel", ctx, provider, token, guildID, channel, text)
	ret0, _ := ret[0].(entity.ChatSendResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendToChannel indicates an expected call of SendToChannel.
func (mr *MockChatCourierMockRecorder) SendToChannel(ctx, provider, token, guildID, channel, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToChannel", reflect.TypeOf((*MockChatCourier)(nil).SendToChannel), ctx, provider, token, guildID, channel, text)
}

// SetWebhook mocks base method.
func (m *MockChatCourier) SetWebhook(ctx context.Context, provider entity.ChatProvider, token, webhookURL, secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWebhook", ctx, provider, token, webhookURL, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWebhook indicates an expected call of SetWebhook.
func (mr *MockChatCourierMockRecorder) SetWebhook(ctx, provider, token, webhookURL, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWebhook", reflect.TypeOf((*MockChatCourier)(nil).SetWebhook), ctx, provider, token, webhookURL, secret)
}

// Validate mocks base method.
func (m *MockChatCourier) Validate(ctx context.Context, provider entity.ChatProvider, token, externalID string) (entity.ChatValidation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, provider, token, externalID)
	ret0, _ := ret[0].(entity.ChatValidation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockChatCourierMockRecorder) Validate(ctx, provider, token, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockChatCourier)(nil).Validate), ctx, provider, token, externalID)
}
