// Code generated by MockGen. DO NOT EDIT.
// Source: silence.go
//
// Generated by this command:
//
//	mockgen -source=silence.go -destination=./silence/silence_mock.go -package=silence
//

// Package silence is a generated GoMock package.
package silence

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSilence is a mock of Silence interface.
type MockSilence struct {
	ctrl     *gomock.Controller
	recorder *MockSilenceMockRecorder
	isgomock struct{}
}

// MockSilenceMockRecorder is the mock recorder for MockSilence.
type MockSilenceMockRecorder struct {
	mock *MockSilence
}

// NewMockSilence creates a new mock instance.
func NewMockSilence(ctrl *gomock.Controller) *MockSilence {
	mock := &MockSilence{ctrl: ctrl}
	mock.recorder = &MockSilenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSilence) EXPECT() *MockSilenceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSilence) Create(ctx context.Context, workspaceID, createdBy, createdByUserID string, in entity.NewSilence) (entity.Silence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceID, createdBy, createdByUserID, in)
	ret0, _ := ret[0].(entity.Silence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSilenceMockRecorder) Create(ctx, workspaceID, createdBy, createdByUserID, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSilence)(nil).Create), ctx, workspaceID, createdBy, createdByUserID, in)
}

// End mocks base method.
func (m *MockSilence) End(ctx context.Context, workspaceID, silenceID string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "End", ctx, workspaceID, silenceID, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// End indicates an expected call of End.
func (mr *MockSilenceMockRecorder) End(ctx, workspaceID, silenceID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSilence)(nil).End), ctx, workspaceID, silenceID, at)
}

// List mocks base method.
func (m *MockSilence) List(ctx context.Context, workspaceID string) ([]entity.Silence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceID)
	ret0, _ := ret[0].([]entity.Silence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSilenceMockRecorder) List(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSilence)(nil).List), ctx, workspaceID)
}

// ListActive mocks base method.
func (m *MockSilence) ListActive(ctx context.Context, workspaceID string, at time.Time) ([]entity.Silence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx, workspaceID, at)
	ret0, _ := ret[0].([]entity.Silence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockSilenceMockRecorder) ListActive(ctx, workspaceID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockSilence)(nil).ListActive), ctx, workspaceID, at)
}
