// Code generated by MockGen. DO NOT EDIT.
// Source: silences.go
//
// Generated by this command:
//
//	mockgen -source=silences.go -destination=./silences/silences_mock.go -package=silences
//

// Package silences is a generated GoMock package.
package silences

import (
	context "context"
	reflect "reflect"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSilences is a mock of Silences interface.
type MockSilences struct {
	ctrl     *gomock.Controller
	recorder *MockSilencesMockRecorder
	isgomock struct{}
}

// MockSilencesMockRecorder is the mock recorder for MockSilences.
type MockSilencesMockRecorder struct {
	mock *MockSilences
}

// NewMockSilences creates a new mock instance.
func NewMockSilences(ctrl *gomock.Controller) *MockSilences {
	mock := &MockSilences{ctrl: ctrl}
	mock.recorder = &MockSilencesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSilences) EXPECT() *MockSilencesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSilences) Create(ctx context.Context, workspaceSlug string, in entity.NewSilence) (entity.Silence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceSlug, in)
	ret0, _ := ret[0].(entity.Silence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSilencesMockRecorder) Create(ctx, workspaceSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSilences)(nil).Create), ctx, workspaceSlug, in)
}

// End mocks base method.
func (m *MockSilences) End(ctx context.Context, workspaceSlug, silenceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "End", ctx, workspaceSlug, silenceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// End indicates an expected call of End.
func (mr *MockSilencesMockRecorder) End(ctx, workspaceSlug, silenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSilences)(nil).End), ctx, workspaceSlug, silenceID)
}

// List mocks base method.
func (m *MockSilences) List(ctx context.Context, workspaceSlug string) ([]entity.Silence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceSlug)
	ret0, _ := ret[0].([]entity.Silence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSilencesMockRecorder) List(ctx, workspaceSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSilences)(nil).List), ctx, workspaceSlug)
}
