// Code generated by MockGen. DO NOT EDIT.
// Source: schedules.go
//
// Generated by this command:
//
//	mockgen -source=schedules.go -destination=./schedules/schedules_mock.go -package=schedules
//

// Package schedules is a generated GoMock package.
package schedules

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/opsybot/opsybot/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSchedules is a mock of Schedules interface.
type MockSchedules struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulesMockRecorder
	isgomock struct{}
}

// MockSchedulesMockRecorder is the mock recorder for MockSchedules.
type MockSchedulesMockRecorder struct {
	mock *MockSchedules
}

// NewMockSchedules creates a new mock instance.
func NewMockSchedules(ctrl *gomock.Controller) *MockSchedules {
	mock := &MockSchedules{ctrl: ctrl}
	mock.recorder = &MockSchedulesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedules) EXPECT() *MockSchedulesMockRecorder {
	return m.recorder
}

// AddOverride mocks base method.
func (m *MockSchedules) AddOverride(ctx context.Context, workspaceSlug, scheduleSlug string, in entity.NewOverride) (entity.Override, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOverride", ctx, workspaceSlug, scheduleSlug, in)
	ret0, _ := ret[0].(entity.Override)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOverride indicates an expected call of AddOverride.
func (mr *MockSchedulesMockRecorder) AddOverride(ctx, workspaceSlug, scheduleSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOverride", reflect.TypeOf((*MockSchedules)(nil).AddOverride), ctx, workspaceSlug, scheduleSlug, in)
}

// Archive mocks base method.
func (m *MockSchedules) Archive(ctx context.Context, workspaceSlug, scheduleSlug string) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Archive indicates an expected call of Archive.
func (mr *MockSchedulesMockRecorder) Archive(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockSchedules)(nil).Archive), ctx, workspaceSlug, scheduleSlug)
}

// Calendar mocks base method.
func (m *MockSchedules) Calendar(ctx context.Context, workspaceSlug, scheduleSlug string, from, to time.Time) (entity.ScheduleCalendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calendar", ctx, workspaceSlug, scheduleSlug, from, to)
	ret0, _ := ret[0].(entity.ScheduleCalendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calendar indicates an expected call of Calendar.
func (mr *MockSchedulesMockRecorder) Calendar(ctx, workspaceSlug, scheduleSlug, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calendar", reflect.TypeOf((*MockSchedules)(nil).Calendar), ctx, workspaceSlug, scheduleSlug, from, to)
}

// Create mocks base method.
func (m *MockSchedules) Create(ctx context.Context, workspaceSlug string, in entity.NewSchedule) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, workspaceSlug, in)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSchedulesMockRecorder) Create(ctx, workspaceSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSchedules)(nil).Create), ctx, workspaceSlug, in)
}

// Delete mocks base method.
func (m *MockSchedules) Delete(ctx context.Context, workspaceSlug, scheduleSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSchedulesMockRecorder) Delete(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSchedules)(nil).Delete), ctx, workspaceSlug, scheduleSlug)
}

// Duplicate mocks base method.
func (m *MockSchedules) Duplicate(ctx context.Context, workspaceSlug, scheduleSlug string) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Duplicate", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Duplicate indicates an expected call of Duplicate.
func (mr *MockSchedulesMockRecorder) Duplicate(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duplicate", reflect.TypeOf((*MockSchedules)(nil).Duplicate), ctx, workspaceSlug, scheduleSlug)
}

// Feed mocks base method.
func (m *MockSchedules) Feed(ctx context.Context, feedToken string) (entity.Schedule, []entity.FeedShift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, feedToken)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].([]entity.FeedShift)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Feed indicates an expected call of Feed.
func (mr *MockSchedulesMockRecorder) Feed(ctx, feedToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockSchedules)(nil).Feed), ctx, feedToken)
}

// Get mocks base method.
func (m *MockSchedules) Get(ctx context.Context, workspaceSlug, scheduleSlug string) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSchedulesMockRecorder) Get(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSchedules)(nil).Get), ctx, workspaceSlug, scheduleSlug)
}

// List mocks base method.
func (m *MockSchedules) List(ctx context.Context, workspaceSlug string, includeArchived bool) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, workspaceSlug, includeArchived)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSchedulesMockRecorder) List(ctx, workspaceSlug, includeArchived any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSchedules)(nil).List), ctx, workspaceSlug, includeArchived)
}

// MyShifts mocks base method.
func (m *MockSchedules) MyShifts(ctx context.Context, workspaceSlug string, from, to time.Time) ([]entity.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MyShifts", ctx, workspaceSlug, from, to)
	ret0, _ := ret[0].([]entity.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MyShifts indicates an expected call of MyShifts.
func (mr *MockSchedulesMockRecorder) MyShifts(ctx, workspaceSlug, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MyShifts", reflect.TypeOf((*MockSchedules)(nil).MyShifts), ctx, workspaceSlug, from, to)
}

// OnCall mocks base method.
func (m *MockSchedules) OnCall(ctx context.Context, workspaceSlug, scheduleSlug string, at time.Time) (entity.Coverage, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCall", ctx, workspaceSlug, scheduleSlug, at)
	ret0, _ := ret[0].(entity.Coverage)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OnCall indicates an expected call of OnCall.
func (mr *MockSchedulesMockRecorder) OnCall(ctx, workspaceSlug, scheduleSlug, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCall", reflect.TypeOf((*MockSchedules)(nil).OnCall), ctx, workspaceSlug, scheduleSlug, at)
}

// Pause mocks base method.
func (m *MockSchedules) Pause(ctx context.Context, workspaceSlug, scheduleSlug string) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pause indicates an expected call of Pause.
func (mr *MockSchedulesMockRecorder) Pause(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockSchedules)(nil).Pause), ctx, workspaceSlug, scheduleSlug)
}

// Preview mocks base method.
func (m *MockSchedules) Preview(ctx context.Context, workspaceSlug string, in entity.NewSchedule, from, to time.Time) (entity.ScheduleCalendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, workspaceSlug, in, from, to)
	ret0, _ := ret[0].(entity.ScheduleCalendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockSchedulesMockRecorder) Preview(ctx, workspaceSlug, in, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockSchedules)(nil).Preview), ctx, workspaceSlug, in, from, to)
}

// Resume mocks base method.
func (m *MockSchedules) Resume(ctx context.Context, workspaceSlug, scheduleSlug string) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockSchedulesMockRecorder) Resume(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockSchedules)(nil).Resume), ctx, workspaceSlug, scheduleSlug)
}

// Unarchive mocks base method.
func (m *MockSchedules) Unarchive(ctx context.Context, workspaceSlug, scheduleSlug string) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unarchive", ctx, workspaceSlug, scheduleSlug)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unarchive indicates an expected call of Unarchive.
func (mr *MockSchedulesMockRecorder) Unarchive(ctx, workspaceSlug, scheduleSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockSchedules)(nil).Unarchive), ctx, workspaceSlug, scheduleSlug)
}

// Update mocks base method.
func (m *MockSchedules) Update(ctx context.Context, workspaceSlug, scheduleSlug string, in entity.ScheduleUpdate) (entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, workspaceSlug, scheduleSlug, in)
	ret0, _ := ret[0].(entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSchedulesMockRecorder) Update(ctx, workspaceSlug, scheduleSlug, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSchedules)(nil).Update), ctx, workspaceSlug, scheduleSlug, in)
}
